window.APP_SPOTS = {
  region: "Riva del Garda",
  center: [45.885, 10.842],
  zoom: 11,
  storageKeys: {
    favorites: "riva_favorites_v2",
    planner:   "riva_day_planner_v2"
  },

  // ── Zone visibili nei filtri ──────────────────────────────────────────────
  zones: [
    { id: "lago",     label: "Lago"     },
    { id: "ovest",    label: "Ovest"    },
    { id: "est",      label: "Est"      },
    { id: "nord",     label: "Nord"     },
    { id: "montagna", label: "Montagna" }
  ],

  // ── Attività visibili nei filtri ──────────────────────────────────────────
  activities: [
    { id: "trekking", label: "Trekking", emoji: "🥾" },
    { id: "mtb",      label: "MTB",      emoji: "🚵" },
    { id: "view",     label: "View",     emoji: "🔭" },
    { id: "relax",    label: "Relax",    emoji: "🌊" },
    { id: "water",    label: "Acqua",    emoji: "🏄" }
  ],

  // ── Top list per home e top page ──────────────────────────────────────────
  topWowNames: [
    "Punta Larici",
    "Sentiero del Ponale",
    "Monte Brione",
    "Bastione di Riva",
    "Monte Altissimo",
    "Lago di Tenno",
    "Busatte Tempesta",
    "Tremalzo Panorama",
    "Belvedere di Pregasina",
    "Lago di Ledro"
  ],

  topSunsetNames: [
    "Monte Brione",
    "Bastione di Riva",
    "Punta Larici",
    "Lungolago Riva",
    "Belvedere di Nago",
    "Monte Altissimo",
    "Torbole Waterfront",
    "Belvedere di Pregasina",
    "Lido di Riva",
    "Lago di Tenno"
  ],

  // ── Spot ──────────────────────────────────────────────────────────────────
  spots: [

    // ═══ CORE ════════════════════════════════════════════════════════════════

    {
      id: "core-0",
      name: "Punta Larici",
      zone: "ovest",
      light: "tramonto",
      activity: "trekking",
      difficulty: "medio",
      level: "core",
      lat: 45.8598,
      lon: 10.8075,
      tags: ["epico", "panorama", "viewpoint", "tramonto", "belvedere", "esperienza forte", "wow"],
      alias: ["larici", "punta larici riva"],
      desc: "Il viewpoint più forte della zona. Balcone naturale enorme sopra il Garda, luce di tramonto fenomenale.",
      tip: "Arriva con almeno 30 min di anticipo. Il cielo pulito fa la differenza totale.",
      weatherNote: "Vento forte rende scomodo stare fermi. Evita con raffiche > 35 km/h.",
      photoTips: "Posizionati verso nord con il lago in primo piano, luce da ovest.",
      experience: { wow: 10, tipo: "trekking panoramico", tempo: "2-4h", mood: "epico" },
      whenToGo: { best: "tramonto", note: "luce bassa e cielo pulito moltiplicano la resa" },
      whenToAvoid: ["vento forte", "temporali", "foschia chiusa"],
      access: { difficolta: "medio", parcheggio: "lato Pregasina", walk: "variabile", strada: "asfaltata ai punti base" },
      crowd: { best: "feriali o anticipo", worst: "tramonti perfetti in weekend" },
      smartTips: ["Highlight assoluto della zona", "Non arrivare all'ultimo minuto"],
      image: "https://picsum.photos/seed/Punta-Larici-Riva/900/600"
    },

    {
      id: "core-1",
      name: "Sentiero del Ponale",
      zone: "ovest",
      light: "giorno",
      activity: "mtb",
      difficulty: "medio",
      level: "core",
      lat: 45.8719,
      lon: 10.8501,
      tags: ["iconico", "MTB panoramica", "bike", "storico", "classico", "esperienza forte"],
      alias: ["ponale", "riva bike", "ciclabile ponale"],
      desc: "La strada panoramica sul lago più famosa della zona. Iconica, leggibile, fortissima da vivere in MTB o a piedi.",
      tip: "Prima delle 9 è un'altra cosa. Evita le ore centrali nei giorni di punta.",
      experience: { wow: 10, tipo: "bike / hike panoramico", tempo: "1-3h", mood: "iconico" },
      whenToGo: { best: "mattina", note: "luce laterale e meno folla" },
      whenToAvoid: ["ore centrali in alta stagione", "meteo instabile forte"],
      access: { difficolta: "medio", parcheggio: "facile da Riva", walk: "0 min", strada: "asfaltata e sterrata" },
      crowd: { best: "presto mattina", worst: "metà mattina nei giorni forti" },
      smartTips: ["Ottimo sia in MTB che a piedi", "Più movimento che spot statico"],
      image: "https://picsum.photos/seed/Ponale-Riva/900/600"
    },

    {
      id: "core-2",
      name: "Monte Brione",
      zone: "lago",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "core",
      lat: 45.8892,
      lon: 10.8595,
      tags: ["tramonto", "viewpoint facile", "panorama", "golden hour", "tramonto rapido", "facile bello"],
      alias: ["brione", "monte brione riva"],
      desc: "Vista alta su Riva, Torbole e tutto il lago nord. Accessibile, forte, perfetto per chiusura giornata.",
      tip: "Uno dei migliori spot tramonto easy della zona. Resa altissima con poco sforzo.",
      experience: { wow: 9, tipo: "viewpoint facile", tempo: "30-90 min", mood: "panorama pulito" },
      whenToGo: { best: "tramonto", note: "luce morbida e aria pulita" },
      whenToAvoid: ["luce dura di mezzogiorno", "foschia"],
      access: { difficolta: "facile", parcheggio: "medio", walk: "breve", strada: "asfaltata" },
      crowd: { best: "arrivo anticipato", worst: "tramonti perfetti" },
      smartTips: ["Piano B eccellente se Larici è troppo lontana", "Molto leggibile anche per chi non conosce la zona"],
      image: "https://picsum.photos/seed/Monte-Brione-Riva/900/600"
    },

    {
      id: "core-3",
      name: "Bastione di Riva",
      zone: "lago",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "core",
      lat: 45.8871,
      lon: 10.8404,
      tags: ["tramonto rapido", "storico", "view", "golden hour", "piano B", "vicino", "tramonto facile"],
      alias: ["bastione", "rocca riva"],
      desc: "Fortezza storica sopra Riva con vista alta sul lago. Tramonto rapido e accessibile, ottimo come piano B.",
      tip: "In golden hour è molto forte. Si abbina bene a una passeggiata nel centro storico.",
      experience: { wow: 9, tipo: "view urbano-lago", tempo: "30-75 min", mood: "forte ma semplice" },
      whenToGo: { best: "tramonto", note: "chiusura facile e soddisfacente" },
      whenToAvoid: ["ore centrali", "meteo piatto"],
      access: { difficolta: "facile", parcheggio: "ottimo in città", walk: "breve salita", strada: "asfaltata" },
      crowd: { best: "feriali", worst: "tramonti perfetti" },
      smartTips: ["Tramonto in 45 minuti porta a porta", "Ideale se sei in centro e vuoi il colpo d'occhio"],
      image: "https://picsum.photos/seed/Bastione-Riva/900/600"
    },

    {
      id: "core-4",
      name: "Monte Altissimo",
      zone: "montagna",
      light: "tramonto",
      activity: "trekking",
      difficulty: "impegnativo",
      level: "core",
      lat: 45.8962,
      lon: 10.8508,
      tags: ["quota", "giornata seria", "grande panorama", "montagna vera", "esperienza forte", "trekking wow"],
      alias: ["altissimo", "monte altissimo di nago"],
      desc: "Grande classico di quota sopra il Garda. Vista enorme, sensazione vera di montagna, giornata intera.",
      tip: "Da fare solo quando sei pronto a dargli una giornata vera. Non sprecarlo con meteo chiuso.",
      weatherNote: "Instabilità pomeridiana frequente. Partenza presto è fondamentale.",
      experience: { wow: 10, tipo: "trekking di quota", tempo: "4-7h", mood: "grande panorama" },
      whenToGo: { best: "giorno", note: "buona visibilità e niente temporali in arrivo" },
      whenToAvoid: ["temporali", "vento forte", "scarsa visibilità"],
      access: { difficolta: "impegnativo", parcheggio: "variabile", walk: "lungo", strada: "asfaltata ai punti base" },
      crowd: { best: "partenza presto", worst: "giorni top stagione" },
      smartTips: ["Tappa centrale, non marginale", "Se il cielo è chiuso, valuta un piano B a quota più bassa"],
      image: "https://picsum.photos/seed/Monte-Altissimo-Riva/900/600"
    },

    {
      id: "core-5",
      name: "Lago di Tenno",
      zone: "nord",
      light: "giorno",
      activity: "relax",
      difficulty: "facile",
      level: "core",
      lat: 45.9381,
      lon: 10.8109,
      tags: ["turchese", "lago relax", "fotogenico", "colori", "spot acqua", "piano B pioggia"],
      alias: ["tenno", "lago tenno", "laghetto tenno"],
      desc: "Lago turchese di forte impatto visivo. Facile, fotogenico, funziona bene anche in giornata grigia.",
      tip: "La mattina presto è il momento migliore per colori e tranquillità.",
      photoTips: "Dal bordo nord con luce mattutina il turchese è al massimo.",
      experience: { wow: 9, tipo: "lago relax", tempo: "1-2h", mood: "relax wow" },
      whenToGo: { best: "mattina", note: "luce che esalta il colore dell'acqua" },
      whenToAvoid: ["metà giornata in alta stagione"],
      access: { difficolta: "facile", parcheggio: "comodo", walk: "breve", strada: "asfaltata" },
      crowd: { best: "presto mattina", worst: "metà giornata estate" },
      smartTips: ["Abbinalo al borgo medievale di Tenno sopra", "Bello anche con cielo coperto leggero"],
      image: "https://picsum.photos/seed/Lago-Tenno-Riva/900/600"
    },

    {
      id: "core-6",
      name: "Busatte Tempesta",
      zone: "est",
      light: "giorno",
      activity: "trekking",
      difficulty: "medio",
      level: "core",
      lat: 45.8778,
      lon: 10.8834,
      tags: ["altalena", "adrenalina", "vista", "esperienza forte", "wow", "diverso", "trekking"],
      alias: ["busatte", "altalena torbole", "tempesta torbole"],
      desc: "Percorso con altalena panoramica leggendaria sopra Torbole. Unico nel suo genere.",
      tip: "Arriva presto per evitare la coda. Il percorso vale anche senza aspettare.",
      experience: { wow: 10, tipo: "hike + adrenalina", tempo: "2-3h", mood: "avventura" },
      whenToGo: { best: "mattina", note: "cielo pulito per il lago luminoso sotto" },
      whenToAvoid: ["meteo chiuso", "weekend alta stagione"],
      access: { difficolta: "medio", parcheggio: "comodo a Torbole", walk: "salita moderata", strada: "asfaltata alla base" },
      crowd: { best: "feriali mattina", worst: "weekend estate" },
      smartTips: ["Ottimo per chi vuole qualcosa di insolito", "Il panorama è già fortissimo a metà percorso"],
      image: "https://picsum.photos/seed/Busatte-Tempesta-Riva/900/600"
    },

    {
      id: "core-7",
      name: "Tremalzo Panorama",
      zone: "ovest",
      light: "giorno",
      activity: "mtb",
      difficulty: "impegnativo",
      level: "core",
      lat: 45.8404,
      lon: 10.7197,
      tags: ["MTB epico", "MTB panoramica", "quota", "giornata seria", "leggenda", "esperienza forte"],
      alias: ["tremalzo", "passo tremalzo"],
      desc: "Il giro MTB più leggendario della zona. Quota, panorama totale, sensazione vera. Giornata intera.",
      tip: "Preparati bene: acqua, cibo, meteo stabile. Non un giro improvvisato.",
      experience: { wow: 10, tipo: "MTB di quota", tempo: "5-8h", mood: "epico" },
      whenToGo: { best: "giorno", note: "cielo pulito fondamentale" },
      whenToAvoid: ["fondo bagnato", "meteo instabile", "pomeriggio in quota"],
      access: { difficolta: "impegnativo", parcheggio: "variabile", walk: "n/a", strada: "sterrata e asfalto" },
      crowd: { best: "feriali fuori stagione", worst: "weekend estate" },
      smartTips: ["Giornata dedicata, non mezza giornata", "Il panorama finale ovest è il migliore dell'area"],
      image: "https://picsum.photos/seed/Tremalzo-Riva/900/600"
    },

    {
      id: "core-8",
      name: "Belvedere di Pregasina",
      zone: "ovest",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "core",
      lat: 45.8649,
      lon: 10.8106,
      tags: ["tramonto rapido", "viewpoint facile", "panorama", "tramonto facile", "facile bello", "garda nord"],
      alias: ["pregasina", "belvedere pregasina"],
      desc: "Belvedere sul Garda nord con accesso facilissimo. Uno dei tramonto più accessibili e soddisfacenti.",
      tip: "Rapido e sicuro. Ottimo se non vuoi rischiare di arrivare tardi al tramonto.",
      experience: { wow: 9, tipo: "viewpoint facile", tempo: "30-60 min", mood: "panorama pulito" },
      whenToGo: { best: "tramonto", note: "lago in controluce fortissimo" },
      whenToAvoid: ["foschia intensa"],
      access: { difficolta: "facile", parcheggio: "nel borgo", walk: "brevissima", strada: "asfaltata" },
      crowd: { best: "feriali", worst: "tramonti stagione" },
      smartTips: ["Abbinalo a Punta Larici se vuoi il tramonto di riserva vicino"],
      image: "https://picsum.photos/seed/Pregasina-Riva/900/600"
    },

    {
      id: "core-9",
      name: "Lago di Ledro",
      zone: "nord",
      light: "giorno",
      activity: "relax",
      difficulty: "facile",
      level: "core",
      lat: 45.8761,
      lon: 10.7479,
      tags: ["lago relax", "ledro", "tranquillo", "bike lago", "giornata lenta", "spot acqua"],
      alias: ["ledro", "lago ledro", "pieve di ledro"],
      desc: "Lago verde e rilassante, ottimo per staccare il ritmo. Bici attorno al lago è un classico.",
      tip: "Ideale come alternativa al Garda per chi vuole silenzio e ritmo lento.",
      experience: { wow: 8, tipo: "lago relax / bike", tempo: "2-4h", mood: "relax" },
      whenToGo: { best: "giorno", note: "tutta la giornata funziona, meglio non troppo caldo" },
      whenToAvoid: ["weekend di agosto"],
      access: { difficolta: "facile", parcheggio: "ampio", walk: "0", strada: "asfaltata" },
      crowd: { best: "feriali", worst: "estate piena" },
      smartTips: ["Museo delle Palafitte da abbinare", "La ciclabile attorno al lago è piacevolissima"],
      image: "https://picsum.photos/seed/Lago-Ledro-Riva/900/600"
    },

    // ═══ SECONDARY ════════════════════════════════════════════════════════════

    {
      id: "secondary-0",
      name: "Belvedere di Nago",
      zone: "est",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "secondary",
      lat: 45.8791,
      lon: 10.8894,
      tags: ["tramonto", "viewpoint facile", "piano B", "nago", "torbole", "tramonto rapido"],
      alias: ["nago", "belvedere nago"],
      desc: "Belvedere valido sopra Torbole, facile e forte al tramonto. Ottimo piano B se Brione è pieno.",
      tip: "Valida alternativa a Monte Brione lato est.",
      experience: { wow: 8, tipo: "viewpoint", tempo: "30-60 min", mood: "panorama" },
      whenToGo: { best: "tramonto", note: "luce tardo pomeriggio molto forte" },
      access: { difficolta: "facile", parcheggio: "comodo", walk: "breve", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Nago-Riva/900/600"
    },

    {
      id: "secondary-1",
      name: "Torbole Waterfront",
      zone: "est",
      light: "giorno",
      activity: "relax",
      difficulty: "facile",
      level: "secondary",
      lat: 45.8703,
      lon: 10.8814,
      tags: ["waterfront", "surf", "windsurf", "vento", "relax lago", "spot acqua", "torbole"],
      alias: ["torbole", "lungolago torbole"],
      desc: "Lungolago di Torbole, vivace e ventoso. Il pomeriggio con vento è spettacolo di windsurf.",
      tip: "Meglio nel pomeriggio quando il vento termico anima il lago.",
      experience: { wow: 7, tipo: "relax lago / windsurf", tempo: "1-3h", mood: "relax" },
      whenToGo: { best: "pomeriggio", note: "vento termico e windsurf al massimo" },
      access: { difficolta: "facile", parcheggio: "comodo", walk: "0", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Torbole-Riva/900/600"
    },

    {
      id: "secondary-2",
      name: "Lungolago Riva",
      zone: "lago",
      light: "tramonto",
      activity: "relax",
      difficulty: "facile",
      level: "secondary",
      lat: 45.8838,
      lon: 10.8417,
      tags: ["lungolago", "passeggiata", "tramonto relax", "sera", "aperitivo", "vicino", "piano B"],
      alias: ["lungolago", "passeggiata riva", "riva centro"],
      desc: "Passeggiata classica sul lungolago di Riva. Ottima per chiudere la giornata con calma.",
      tip: "Con aperitivo al tramonto è una chiusura classica e soddisfacente.",
      experience: { wow: 7, tipo: "passeggiata sera", tempo: "30-90 min", mood: "relax" },
      whenToGo: { best: "tramonto", note: "passeggiata serale classica" },
      access: { difficolta: "facile", parcheggio: "ottimo in città", walk: "0", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Lungolago-Riva/900/600"
    },

    {
      id: "secondary-3",
      name: "Lido di Riva",
      zone: "lago",
      light: "giorno",
      activity: "relax",
      difficulty: "facile",
      level: "secondary",
      lat: 45.8821,
      lon: 10.8461,
      tags: ["spiaggia", "lago relax", "spot acqua", "bagno", "estate", "vicino"],
      alias: ["lido riva", "spiaggia riva", "spiagge riva del garda"],
      desc: "Spiaggia principale di Riva. Comoda, servita, ottima nelle giornate calde.",
      tip: "Mattina presto per stare tranquilli. Pomeriggio è molto frequentata.",
      experience: { wow: 6, tipo: "spiaggia lago", tempo: "2-4h", mood: "relax" },
      whenToGo: { best: "mattina", note: "meno folla, acqua più fresca" },
      access: { difficolta: "facile", parcheggio: "a pagamento vicino", walk: "0", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Lido-Riva/900/600"
    },

    {
      id: "secondary-4",
      name: "Arco Castello",
      zone: "nord",
      light: "giorno",
      activity: "view",
      difficulty: "facile",
      level: "secondary",
      lat: 45.9218,
      lon: 10.8892,
      tags: ["castello", "storico", "viewpoint facile", "arco", "panorama valle", "facile bello"],
      alias: ["castello arco", "arco", "rocca arco"],
      desc: "Castello medievale iconico sopra Arco. Vista fortissima sulla valle del Sarca e sul Garda.",
      tip: "Abbinalo alla visita di Arco. Mattina per la luce migliore sulla valle.",
      experience: { wow: 8, tipo: "viewpoint storico", tempo: "1-2h", mood: "storico" },
      whenToGo: { best: "mattina", note: "luce sulla valle più morbida" },
      access: { difficolta: "facile", parcheggio: "comodo in città", walk: "salita breve", strada: "asfaltata" },
      crowd: { best: "feriali", worst: "alta stagione" },
      image: "https://picsum.photos/seed/Arco-Castello-Riva/900/600"
    },

    {
      id: "secondary-5",
      name: "Busatte Park Easy",
      zone: "est",
      light: "giorno",
      activity: "trekking",
      difficulty: "facile",
      level: "secondary",
      lat: 45.8773,
      lon: 10.8859,
      tags: ["trekking facile", "verde", "torbole", "piano B", "sentiero easy", "vicino"],
      alias: ["busatte easy", "parco busatte"],
      desc: "Zona verde sopra Torbole. Sentiero facile, bella come alternativa rilassata a Busatte Tempesta.",
      tip: "Piano B ideale se non vuoi la salita impegnativa ma vuoi stare nella natura.",
      experience: { wow: 6, tipo: "passeggiata natura", tempo: "1-2h", mood: "relax" },
      whenToGo: { best: "giorno", note: "qualsiasi ora funziona" },
      access: { difficolta: "facile", parcheggio: "comodo a Torbole", walk: "breve", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Busatte-Park-Riva/900/600"
    },

    {
      id: "secondary-6",
      name: "Tempesta Lago",
      zone: "est",
      light: "tramonto",
      activity: "relax",
      difficulty: "facile",
      level: "secondary",
      lat: 45.8608,
      lon: 10.8928,
      tags: ["tramonto", "relax lago", "tranquillo", "alternativo", "est"],
      alias: ["tempesta", "garda nord-est"],
      desc: "Zona tranquilla dell'estremo nord-est del Garda. Piacevole come sosta diversa e silenziosa.",
      tip: "Bella quando vuoi staccare dalla folla di Riva e Torbole.",
      experience: { wow: 6, tipo: "sosta lago", tempo: "30-60 min", mood: "relax" },
      whenToGo: { best: "tramonto", note: "ora più silenziosa e bella" },
      access: { difficolta: "facile", parcheggio: "comodo", walk: "0", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Tempesta-Riva/900/600"
    },

    {
      id: "secondary-7",
      name: "Arco Olive Trail",
      zone: "nord",
      light: "giorno",
      activity: "trekking",
      difficulty: "facile",
      level: "secondary",
      lat: 45.9181,
      lon: 10.8882,
      tags: ["ulivi", "sentiero facile", "arco", "trekking easy", "natura", "verde"],
      alias: ["sentiero ulivi", "arco trekking", "olivi arco"],
      desc: "Sentiero tra gli ulivi nell'area di Arco. Facile, profumato, piacevole senza stress.",
      tip: "Ottimo per chi vuole camminare senza impegno in un paesaggio bello.",
      experience: { wow: 7, tipo: "trekking facile", tempo: "1-2h", mood: "relax" },
      whenToGo: { best: "mattina", note: "fresco e luce laterale sugli ulivi" },
      access: { difficolta: "facile", parcheggio: "comodo ad Arco", walk: "partenza dal centro", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Arco-Olive-Riva/900/600"
    },

    {
      id: "secondary-8",
      name: "Ceniga Riverside",
      zone: "nord",
      light: "giorno",
      activity: "relax",
      difficulty: "facile",
      level: "secondary",
      lat: 45.9362,
      lon: 10.9161,
      tags: ["fiume", "relax", "sarca", "tranquillo", "alternativo lago"],
      alias: ["ceniga", "fiume sarca", "sarca ceniga"],
      desc: "Riva del Sarca in zona Ceniga. Tranquilla, verde, ottima alternativa al lago per chi vuole fresco e silenzio.",
      tip: "Molto soft. Ideale nelle ore calde come pausa fresca.",
      experience: { wow: 6, tipo: "relax fiume", tempo: "30-90 min", mood: "relax" },
      whenToGo: { best: "pomeriggio", note: "fresco naturale nelle ore più calde" },
      access: { difficolta: "facile", parcheggio: "comodo", walk: "breve", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Ceniga-Riva/900/600"
    },

    {
      id: "secondary-9",
      name: "Varone Cascate",
      zone: "nord",
      light: "giorno",
      activity: "relax",
      difficulty: "facile",
      level: "secondary",
      lat: 45.9018,
      lon: 10.8516,
      tags: ["cascate", "natura", "fresco", "alternativo", "curiosità", "vicino riva"],
      alias: ["varone", "cascata varone", "gorge varone"],
      desc: "Gola con cascate a pochi minuti da Riva. Fresca, suggestiva, ottima come tappa diversa.",
      tip: "Ingresso a pagamento ma vale come sosta curiosa. Fresco anche in estate.",
      experience: { wow: 7, tipo: "visita cascate", tempo: "45-90 min", mood: "curiosità" },
      whenToGo: { best: "giorno", note: "bello in qualsiasi condizione meteo" },
      access: { difficolta: "facile", parcheggio: "comodo", walk: "breve", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Varone-Riva/900/600"
    },

    {
      id: "secondary-10",
      name: "Walking Lago di Ledro",
      zone: "nord",
      light: "giorno",
      activity: "relax",
      difficulty: "facile",
      level: "secondary",
      lat: 45.8793,
      lon: 10.7441,
      tags: ["passeggiata", "ledro", "lago relax", "giornata lenta", "easy"],
      alias: ["passeggiata ledro", "giro ledro"],
      desc: "Passeggiata semplice attorno al Lago di Ledro. Piacevole, flat, ottima per abbassare il ritmo.",
      tip: "Perfetta per chi vuole muoversi senza fatica in un paesaggio tranquillo.",
      experience: { wow: 6, tipo: "passeggiata lago", tempo: "1-2h", mood: "relax" },
      whenToGo: { best: "giorno", note: "tutta la giornata funziona" },
      access: { difficolta: "facile", parcheggio: "ampio", walk: "0", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Walking-Ledro-Riva/900/600"
    },

    {
      id: "secondary-11",
      name: "Ledro Bike Tour",
      zone: "nord",
      light: "giorno",
      activity: "mtb",
      difficulty: "facile",
      level: "secondary",
      lat: 45.8761,
      lon: 10.7479,
      tags: ["bike", "MTB panoramica", "ledro", "giro lago", "mtb facile", "giornata morbida"],
      alias: ["bike ledro", "ciclabile ledro", "mtb ledro"],
      desc: "Giro in bici attorno al Lago di Ledro. Facile, godibile, ottimo per una giornata più soft.",
      tip: "Ideale come alternativa al Ponale per chi vuole la bici senza impegno.",
      experience: { wow: 7, tipo: "MTB facile lago", tempo: "1-2h", mood: "relax" },
      whenToGo: { best: "mattina", note: "fresco e poco traffico" },
      access: { difficolta: "facile", parcheggio: "ampio", walk: "0", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Ledro-Bike-Riva/900/600"
    },

    {
      id: "secondary-12",
      name: "Bocca di Trat",
      zone: "montagna",
      light: "giorno",
      activity: "trekking",
      difficulty: "medio",
      level: "secondary",
      lat: 45.8677,
      lon: 10.7501,
      tags: ["quota", "pascoli", "panorama", "alternativo", "meno mainstream", "trekking"],
      alias: ["bocca trat", "trat"],
      desc: "Quota sopra il Ledro con pascoli e grande senso di spazio. Meno nota del mainstream, molto bella.",
      tip: "Ottima per chi vuole la montagna vera senza incontrare troppa gente.",
      experience: { wow: 8, tipo: "trekking quota", tempo: "3-5h", mood: "avventura" },
      whenToGo: { best: "giorno", note: "luce pulita mattutina per i panorami" },
      whenToAvoid: ["meteo instabile"],
      access: { difficolta: "medio", parcheggio: "base valle", walk: "salita", strada: "sterrata finale" },
      image: "https://picsum.photos/seed/Bocca-di-Trat-Riva/900/600"
    },

    {
      id: "secondary-13",
      name: "Belvedere di Dromaé",
      zone: "nord",
      light: "tramonto",
      activity: "view",
      difficulty: "medio",
      level: "secondary",
      lat: 45.8872,
      lon: 10.7368,
      tags: ["belvedere", "ledro", "panorama", "tramonto", "alternativo", "meno mainstream"],
      alias: ["dromae", "dromaé", "belvedere ledro"],
      desc: "Belvedere ampio sopra il Ledro, poco conosciuto ma di grande qualità. Tramonto diverso dal solito.",
      tip: "Ottimo se vuoi un tramonto alternativo fuori dai circuiti più frequentati.",
      experience: { wow: 8, tipo: "viewpoint", tempo: "1-2h", mood: "panorama" },
      whenToGo: { best: "tramonto", note: "luce serale molto bella sul Ledro" },
      access: { difficolta: "medio", parcheggio: "limitato", walk: "salita", strada: "sterrata finale" },
      image: "https://picsum.photos/seed/Dromae-Riva/900/600"
    },

    {
      id: "secondary-14",
      name: "Madonnina di Besta",
      zone: "nord",
      light: "tramonto",
      activity: "view",
      difficulty: "medio",
      level: "secondary",
      lat: 45.8878,
      lon: 10.7268,
      tags: ["viewpoint", "ledro", "tramonto", "mistico", "alternativo", "meno mainstream"],
      alias: ["besta", "madonnina besta"],
      desc: "Viewpoint raccolto e suggestivo sulla valle di Ledro. Luce di tramonto molto bella, posto meno battuto.",
      tip: "Per chi vuole qualcosa di diverso e silenzioso. Non ci trovi folla.",
      experience: { wow: 8, tipo: "viewpoint raccolto", tempo: "1-2h", mood: "mistico" },
      whenToGo: { best: "tramonto", note: "luce calda sulla valle" },
      access: { difficolta: "medio", parcheggio: "limitato", walk: "salita", strada: "sterrata" },
      image: "https://picsum.photos/seed/Besta-Riva/900/600"
    },

    {
      id: "secondary-15",
      name: "Monte Corno Ledro",
      zone: "montagna",
      light: "giorno",
      activity: "trekking",
      difficulty: "impegnativo",
      level: "secondary",
      lat: 45.9051,
      lon: 10.7246,
      tags: ["cima", "giornata seria", "montagna vera", "ledro", "trekking wow", "meno mainstream"],
      alias: ["corno ledro", "monte corno"],
      desc: "Cima vera sopra il Ledro. Bella, impegnativa, meno nota dell'Altissimo. Per chi vuole montagna autentica.",
      tip: "Alternativa seria all'Altissimo per chi cerca qualcosa fuori dai radar.",
      experience: { wow: 8, tipo: "trekking di cima", tempo: "4-6h", mood: "grande panorama" },
      whenToGo: { best: "giorno", note: "partenza presto, meteo stabile" },
      whenToAvoid: ["temporali", "meteo instabile"],
      access: { difficolta: "impegnativo", parcheggio: "base valle", walk: "lungo", strada: "sterrata" },
      image: "https://picsum.photos/seed/Monte-Corno-Ledro-Riva/900/600"
    },

    {
      id: "secondary-16",
      name: "Kayak Easy Session",
      zone: "lago",
      light: "mattina",
      activity: "water",
      difficulty: "facile",
      level: "secondary",
      lat: 45.8849,
      lon: 10.8444,
      tags: ["kayak", "spot acqua", "mattina calma", "sport acqua", "esperienza acqua"],
      alias: ["kayak riva", "canoa riva"],
      desc: "Sessione kayak facile sul Garda. Meglio la mattina quando l'acqua è calma e il vento non c'è ancora.",
      tip: "Evita il pomeriggio con vento termico. La mattina è perfetta.",
      experience: { wow: 7, tipo: "sport acqua", tempo: "1-3h", mood: "avventura" },
      whenToGo: { best: "mattina", note: "lago calmo prima del vento termico" },
      whenToAvoid: ["pomeriggio ventoso"],
      access: { difficolta: "facile", parcheggio: "comodo a Riva", walk: "0", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Kayak-Riva/900/600"
    },

    {
      id: "secondary-17",
      name: "SUP Sunset Session",
      zone: "lago",
      light: "tramonto",
      activity: "water",
      difficulty: "facile",
      level: "secondary",
      lat: 45.8839,
      lon: 10.8435,
      tags: ["sup", "spot acqua", "tramonto acqua", "acqua calma", "esperienza acqua", "serale"],
      alias: ["sup riva", "stand up paddle riva"],
      desc: "SUP serale sul Garda con il tramonto. Bella se l'acqua è calma, esperienza rilassante e visiva.",
      tip: "La sera il vento termico si calma. Scegli serate con acqua ferma.",
      experience: { wow: 8, tipo: "SUP serale", tempo: "1-2h", mood: "relax" },
      whenToGo: { best: "tramonto", note: "vento calmo dopo le 18-19" },
      whenToAvoid: ["pomeriggio con vento termico forte"],
      access: { difficolta: "facile", parcheggio: "comodo a Riva", walk: "0", strada: "asfaltata" },
      image: "https://picsum.photos/seed/SUP-Sunset-Riva/900/600"
    },

    {
      id: "secondary-18",
      name: "Tremalzo Access View",
      zone: "ovest",
      light: "giorno",
      activity: "view",
      difficulty: "medio",
      level: "secondary",
      lat: 45.8461,
      lon: 10.7232,
      tags: ["tremalzo", "viewpoint", "panorama ovest", "MTB panoramica", "modulo leggero"],
      alias: ["tremalzo view", "tremalzo easy", "passo tremalzo view"],
      desc: "Punto panoramico nell'area Tremalzo senza fare il giro epico completo. Molto bello, meno impegnativo.",
      tip: "Ideale se vuoi il panorama del Tremalzo senza investire una giornata intera.",
      experience: { wow: 8, tipo: "viewpoint quota", tempo: "2-4h", mood: "panorama" },
      whenToGo: { best: "giorno", note: "luce pulita per il panorama" },
      access: { difficolta: "medio", parcheggio: "base", walk: "salita", strada: "sterrata" },
      image: "https://picsum.photos/seed/Tremalzo-Access-Riva/900/600"
    },

    {
      id: "secondary-19",
      name: "Monte Baldo Easy View",
      zone: "montagna",
      light: "giorno",
      activity: "view",
      difficulty: "facile",
      level: "secondary",
      lat: 45.7568,
      lon: 10.8088,
      tags: ["baldo", "quota", "viewpoint facile", "panorama garda", "variante smart"],
      alias: ["baldo easy", "monte baldo", "baldo view"],
      desc: "Accesso facile alla quota del Baldo con panorama sul Garda. Variante smart senza il trekking completo.",
      tip: "Se vuoi la quota e il panorama del Baldo senza impegno fisico, questa è la scelta.",
      experience: { wow: 8, tipo: "viewpoint quota facile", tempo: "1-3h", mood: "panorama" },
      whenToGo: { best: "giorno", note: "cielo pulito per vedere tutto il Garda" },
      access: { difficolta: "facile", parcheggio: "comodo", walk: "breve", strada: "asfaltata" },
      image: "https://picsum.photos/seed/Baldo-Easy-Riva/900/600"
    },

    // ═══ EXTRA ════════════════════════════════════════════════════════════════

    {
      id: "extra-0",
      name: "Spiaggia Sabbioni",
      zone: "lago",
      light: "giorno",
      activity: "relax",
      difficulty: "facile",
      level: "extra",
      lat: 45.8802,
      lon: 10.8493,
      tags: ["spiaggia", "relax", "vicino", "bagno", "spot acqua"],
      alias: ["sabbioni", "spiaggia riva nord"],
      desc: "Spiaggia ghiaiosa a nord di Riva. Stop facile per un bagno o una pausa.",
      tip: "Comoda, vicina. Nessun wow ma funzionale.",
      image: "https://picsum.photos/seed/Sabbioni-Riva/900/600"
    },

    {
      id: "extra-1",
      name: "Marina Riva Pause",
      zone: "lago",
      light: "sera",
      activity: "relax",
      difficulty: "facile",
      level: "extra",
      lat: 45.8857,
      lon: 10.8408,
      tags: ["marina", "porto", "sera", "barche", "chiusura giornata"],
      alias: ["porto riva", "marina riva"],
      desc: "Zona porto di Riva, bella come pausa serale tra le barche.",
      tip: "Chiusura piacevole dopo cena o tramonto.",
      image: "https://picsum.photos/seed/Marina-Riva/900/600"
    },

    {
      id: "extra-2",
      name: "Nago Short View",
      zone: "est",
      light: "giorno",
      activity: "view",
      difficulty: "facile",
      level: "extra",
      lat: 45.8791,
      lon: 10.8894,
      tags: ["nago", "view rapido", "torbole", "piano B", "vicino"],
      alias: ["nago view", "vista nago"],
      desc: "Vista rapida sopra Torbole. Modesta ma valida se sei già in zona.",
      tip: "Da fare se passi da Nago e hai 20 minuti.",
      image: "https://picsum.photos/seed/Nago-Short-Riva/900/600"
    },

    {
      id: "extra-3",
      name: "Mezzolago Stop",
      zone: "nord",
      light: "giorno",
      activity: "relax",
      difficulty: "facile",
      level: "extra",
      lat: 45.8886,
      lon: 10.7338,
      tags: ["mezzolago", "ledro", "sosta", "relax", "pausa"],
      alias: ["mezzolago"],
      desc: "Piccola sosta sul Lago di Ledro. Tranquilla, senza pretese, piacevole.",
      tip: "Buona pausa intermedia durante il giro del Ledro.",
      image: "https://picsum.photos/seed/Mezzolago-Riva/900/600"
    },

    {
      id: "extra-4",
      name: "Gelato vista lago",
      zone: "lago",
      light: "sera",
      activity: "relax",
      difficulty: "facile",
      level: "extra",
      lat: 45.8834,
      lon: 10.8412,
      tags: ["gelato", "sera", "chiusura giornata", "vicino", "relax"],
      alias: ["gelato riva", "gelateria lago"],
      desc: "Stop gelato con vista lago a Riva. Chiusura leggera e soddisfacente di qualsiasi giornata.",
      tip: "Il classico finale. Funziona sempre.",
      image: "https://picsum.photos/seed/Gelato-Lago-Riva/900/600"
    }

  ]
};
