window.APP_SPOTS = {
  region: "Madeira",
  center: [32.75, -16.95],
  zoom: 10,

  storageKeys: {
    favorites: "madeira_favorites_v9",
    planner:   "madeira_day_planner_v9"
  },

  // ── Zone ────────────────────────────────────────────────────────────────────
  zones: [
    { id: "est",      label: "Est"      },
    { id: "ovest",    label: "Ovest"    },
    { id: "nord",     label: "Nord"     },
    { id: "sud",      label: "Sud"      },
    { id: "montagna", label: "Montagna" }
  ],

  // ── Attività ─────────────────────────────────────────────────────────────────
  activities: [
    { id: "trekking", label: "Trekking", emoji: "🥾" },
    { id: "view",     label: "View",     emoji: "🔭" },
    { id: "relax",    label: "Relax",    emoji: "🌊" },
    { id: "mtb",      label: "MTB",      emoji: "🚵" },
    { id: "water",    label: "Acqua",    emoji: "🏄" }
  ],

  // ── Top list ──────────────────────────────────────────────────────────────────
  // FIX 11: ID usati per lookup robusto — i nomi sono mantenuti per retrocompatibilità
  topWowIds: [
    "core-0",
    "core-1",
    "core-2",
    "core-3",
    "core-4",
    "core-5",
    "core-6",
    "core-7",
    "core-8",
    "core-11"
  ],
  topWowNames: [
    "Ponta de São Lourenço",
    "Pico do Arieiro",
    "Pico Ruivo Summit",
    "PR1 Arieiro → Ruivo",
    "Fanal Forest",
    "Ribeira da Janela",
    "Porto Moniz Pools",
    "Cabo Girão",
    "Bica da Cana",
    "Eira do Serrado"
  ],

  topSunsetIds: [
    "core-9",
    "core-14",
    "core-7",
    "secondary-0",
    "secondary-17",
    "secondary-18",
    "secondary-23",
    "secondary-22",
    "core-6"
  ],
  topSunsetNames: [
    "Ponta do Pargo Lighthouse",
    "Câmara de Lobos",
    "Cabo Girão",
    "Ponta do Sol",
    "Pico dos Barcelos",
    "Miradouro do Pináculo",
    "Jardim do Mar View",
    "Paul do Mar",
    "Porto Moniz Pools"
  ],

  // ── Spots ──────────────────────────────────────────────────────────────────────
  spots: [

    // ═══ CORE ══════════════════════════════════════════════════════════════════

    {
      id: "core-0",
      name: "Ponta de São Lourenço",
      zone: "est",
      light: "alba",
      activity: "trekking",
      difficulty: "medio",
      level: "core",
      priority: 10,
      lat: 32.744,
      lon: -16.704,
      tags: ["sunrise", "sea cliffs", "dramatic coast", "promontory", "wow", "esperienza forte", "trekking panoramico", "giornata seria"],
      alias: ["sao lourenco", "ponta sao lourenco", "east point madeira"],
      desc: "Il promontorio più scenografico del lato est: creste, oceano e senso di grande viaggio.",
      tip: "Arriva 45-60 minuti prima dell'alba. Più tempo hai, meglio vivi lo spot.",
      longDescription: "È uno degli spot più iconici di Madeira e uno di quelli che danno di più anche emotivamente. Non è solo bello: ti fa sentire di essere in un posto speciale. Ideale come giornata forte o come grande inizio viaggio.",
      photoTips: "Luce bassa e laterale, linee della costa, contrasti terra-mare. Evita le ore centrali se vuoi il massimo.",
      experience: { wow: 10, tipo: "trekking panoramico di cresta", tempo: "2-4h", mood: "epico" },
      whenToGo: { best: "alba", note: "Top con luce pulita, cielo discreto e vento non troppo forte." },
      whenToAvoid: ["vento forte", "ore centrali calde", "giornata già piena di spostamenti"],
      access: { difficolta: "medio", parcheggio: "facile vicino all'inizio", walk: "0 min", strada: "asfaltata" },
      crowd: { best: "molto presto", worst: "metà mattina" },
      smartTips: [
        "Porta acqua: il sole si sente più di quanto sembri.",
        "Anche il primo tratto, se sei corto di tempo, vale tanto.",
        "Non serve finire tutto il percorso: il meglio è nei primi chilometri."
      ],
      image: "https://picsum.photos/seed/Ponta-de-Sao-Lourenco-Madeira/900/600"
    },

    {
      id: "core-1",
      name: "Pico do Arieiro",
      zone: "montagna",
      light: "alba",
      activity: "view",
      difficulty: "facile",
      level: "core",
      priority: 10,
      lat: 32.7354,
      lon: -16.9281,
      tags: ["sunrise", "above the clouds", "sea of clouds", "quota", "iconico", "wow", "easy sunrise", "mountain top"],
      alias: ["arieiro", "pico arieiro", "arieiro summit"],
      desc: "Il classico sopra le nuvole: tra i punti più iconici e spettacolari dell'isola.",
      tip: "Arriva prima dell'alba e vestiti bene. Il freddo qui si sente sempre.",
      longDescription: "Quando funziona, questo è il Madeira poster shot: creste, nuvole sotto quota e luce che entra sulle montagne. È uno di quei posti che, se trovi la giornata giusta, rimangono impressi.",
      photoTips: "Lavora con silhouette, profondità e nuvole. Se il mare di nuvole c'è, hai già metà del lavoro fatto.",
      experience: { wow: 10, tipo: "view alta quota", tempo: "30-90 min", mood: "iconico" },
      whenToGo: { best: "alba", note: "Meglio con mare di nuvole e visibilità almeno discreta." },
      whenToAvoid: ["copertura uniforme alta", "vento forte", "visibilità pessima"],
      access: { difficolta: "facile", parcheggio: "diretto ma si riempie", walk: "0-5 min", strada: "asfaltata" },
      crowd: { best: "molto presto", worst: "alba di alta stagione" },
      smartTips: [
        "Porta giacca antivento anche se giù fa caldo.",
        "Aspetta qualche minuto dopo l'alba: la luce migliore arriva spesso lì.",
        "Se è chiuso davvero, non fissarti: cambia spot senza rimpianti."
      ],
      image: "https://picsum.photos/seed/Pico-do-Arieiro-Madeira/900/600"
    },

    {
      id: "core-2",
      name: "Pico Ruivo Summit",
      zone: "montagna",
      light: "alba",
      activity: "trekking",
      difficulty: "impegnativo",
      level: "core",
      priority: 10,
      lat: 32.7591,
      lon: -16.9431,
      tags: ["highest peak", "sunrise", "mountain summit", "quota", "wow", "giornata seria", "grande panorama", "esperienza forte"],
      alias: ["ruivo", "pico ruivo", "highest point madeira"],
      desc: "La cima più alta di Madeira: vista enorme quando il cielo collabora.",
      tip: "Via Achada do Teixeira è la più gestibile. Parti presto.",
      longDescription: "È uno degli spot che alzano davvero il livello del viaggio. Più che una tappa veloce, è un obiettivo serio. Se arrivi quassù con buona visibilità, la sensazione di spazio è fortissima.",
      photoTips: "Meglio alba o prime ore. Con aria limpida lavora su piani lontani e linee pulite.",
      experience: { wow: 10, tipo: "cima panoramica", tempo: "2-4h da Achada do Teixeira", mood: "grande panorama" },
      whenToGo: { best: "alba", note: "Molto meglio con aria limpida e vento contenuto." },
      whenToAvoid: ["nuvole basse persistenti", "vento forte", "scarpe inadatte"],
      access: { difficolta: "impegnativo", parcheggio: "più comodo da Achada do Teixeira", walk: "circa 1h30 da Achada do Teixeira", strada: "asfaltata" },
      crowd: { best: "prestissimo", worst: "mattina media" },
      smartTips: [
        "Porta uno strato caldo vero.",
        "La visibilità conta tantissimo: se è chiuso, l'esperienza perde molto.",
        "Non abbinarlo ad Arieiro lo stesso giorno se hai meno di 8 ore disponibili."
      ],
      image: "https://picsum.photos/seed/Pico-Ruivo-Madeira/900/600"
    },

    {
      id: "core-3",
      name: "PR1 Arieiro → Ruivo",
      zone: "montagna",
      light: "alba",
      activity: "trekking",
      difficulty: "impegnativo",
      level: "core",
      priority: 10,
      lat: 32.7355,
      lon: -16.9288,
      tags: ["iconic trail", "ridge walk", "tunnel", "sunrise", "giornata seria", "esperienza forte", "trekking wow", "mountain traverse"],
      alias: ["pr1", "arieiro ruivo traverse", "traversata arieiro ruivo", "levada alta quota"],
      desc: "Il trekking simbolo di Madeira: creste, tunnel e paesaggio da grande giornata.",
      tip: "Da fare con meteo stabile, gambe buone e partenza prestissimo.",
      longDescription: "È il percorso iconico di alta quota dell'isola. Non fai solo uno spot: fai un'esperienza intera. Se ami le uscite memorabili, è uno di quei giorni da costruire bene e vivere come evento principale.",
      photoTips: "Luce bassa, nuvole dinamiche, creste in profondità. Controlla sempre le condizioni prima.",
      experience: { wow: 10, tipo: "trekking iconico alta quota", tempo: "4-6h", mood: "avventura" },
      whenToGo: { best: "alba", note: "Parti molto presto per avere visibilità e prima luce." },
      whenToAvoid: ["vento forte", "visibilità bassa", "meteo instabile"],
      access: { difficolta: "impegnativo", parcheggio: "facile lato Arieiro", walk: "0 min", strada: "asfaltata" },
      crowd: { best: "partenza prima dell'alba", worst: "metà mattina nei mesi caldi" },
      smartTips: [
        "Porta torcia per i tunnel.",
        "Controlla apertura e condizioni del percorso: può essere chiuso.",
        "Usalo come esperienza centrale della giornata, non come riempitivo."
      ],
      image: "https://picsum.photos/seed/PR1-Arieiro-Ruivo-Madeira/900/600"
    },

    {
      id: "core-4",
      name: "Fanal Forest",
      zone: "ovest",
      light: "giorno",
      activity: "trekking",
      difficulty: "facile",
      level: "core",
      priority: 9,
      lat: 32.7603,
      lon: -17.1476,
      tags: ["forest", "fog", "laurisilva", "mistico", "atmospheric", "piano B pioggia", "nuvole", "trees"],
      alias: ["fanal", "laurel forest madeira", "foresta fanal", "foresta laurisilva"],
      desc: "Foresta magica con alberi contorti e atmosfera unica. Qui il brutto tempo è un vantaggio.",
      tip: "Se trovi nebbia o foschia, hai fatto centro. Con sole forte perde molto.",
      longDescription: "È completamente diversa dal resto di Madeira. Conta meno il grande panorama e molto di più l'atmosfera. Quando c'è nebbia o aria umida, diventa uno degli spot più forti e fotogenici dell'isola.",
      photoTips: "Cerca scene semplici, alberi isolati, profondità morbida. Niente di costruito: basta guardare.",
      experience: { wow: 9, tipo: "foresta atmosferica", tempo: "1-2h", mood: "mistico" },
      whenToGo: { best: "giorno", note: "Le giornate grigie qui sono un vantaggio, non un problema." },
      whenToAvoid: ["sole forte", "giornata troppo limpida e secca"],
      access: { difficolta: "facile", parcheggio: "vicino", walk: "0-5 min", strada: "asfaltata" },
      crowd: { best: "meteo incerto", worst: "giornate molto social e influencer" },
      smartTips: [
        "Piano B eccellente quando il meteo chiude la montagna alta.",
        "Cammina un po' oltre la zona più immediata: l'atmosfera migliora.",
        "Non cercare il sole: cerca la nebbia."
      ],
      image: "https://picsum.photos/seed/Fanal-Forest-Madeira/900/600"
    },

    {
      id: "core-5",
      name: "Ribeira da Janela",
      zone: "nord",
      light: "alba",
      activity: "view",
      difficulty: "facile",
      level: "core",
      priority: 9,
      lat: 32.8652,
      lon: -17.1446,
      tags: ["sea rocks", "ocean", "north coast", "sunrise", "fotogenico", "classico fotografico", "costa drammatica"],
      alias: ["ribeira janela", "rocks ribeira", "janela rocks"],
      desc: "Rocce in mare tra le più iconiche e fotogeniche di Madeira. Resa altissima con luce giusta.",
      tip: "Rende molto meglio con mare vivo e luce bassa. Non fermarti a mezzogiorno.",
      longDescription: "È uno degli spot marini più forti dell'isola. Visivamente semplice da capire ma molto potente. Se prendi bene la luce e un minimo di movimento del mare, la resa è altissima.",
      photoTips: "Alba, onde leggere, cielo con struttura. Lavora sulle rocce e sul respiro del mare.",
      experience: { wow: 9, tipo: "costa rocciosa iconica", tempo: "20-40 min", mood: "classico fotografico" },
      whenToGo: { best: "alba", note: "Top con mare un po' vivo e luce bassa." },
      whenToAvoid: ["mare troppo piatto", "luce dura di mezzogiorno", "meteo spento"],
      access: { difficolta: "facile", parcheggio: "vicino", walk: "2 min", strada: "asfaltata" },
      crowd: { best: "molto presto", worst: "orari comodi" },
      smartTips: [
        "Ottimo in combo con Seixal Beach e Porto Moniz.",
        "Non serve restarci troppo se hai preso la luce giusta.",
        "Il mare agitato aumenta molto il valore dello spot."
      ],
      image: "https://picsum.photos/seed/Ribeira-da-Janela-Madeira/900/600"
    },

    {
      id: "core-6",
      name: "Porto Moniz Pools",
      zone: "nord",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "core",
      priority: 9,
      lat: 32.8664,
      lon: -17.1666,
      tags: ["volcanic pools", "lava pools", "sunset", "ocean", "tramonto", "nord ovest", "tappa iconica"],
      alias: ["porto moniz", "piscine porto moniz", "natural pools madeira"],
      desc: "Piscine vulcaniche e oceano aperto. Tappa forte e molto leggibile, meglio a luce morbida.",
      tip: "Non venirci a mezzogiorno. Funziona meglio come finale di una giornata sul nord-ovest.",
      longDescription: "Roccia vulcanica, acqua, orizzonte e atmosfera. Funziona molto bene come tappa finale di una giornata sul nord-ovest. Semplice da capire, soddisfacente da vivere.",
      photoTips: "Tardo pomeriggio e fine luce. Le rocce prendono carattere quando il contrasto si abbassa.",
      experience: { wow: 8, tipo: "piscine vulcaniche oceaniche", tempo: "1-2h", mood: "scenico e facile" },
      whenToGo: { best: "tramonto", note: "Meglio tardi che nel mezzo della giornata." },
      whenToAvoid: ["mezzogiorno pieno", "vento molto forte con spruzzi"],
      access: { difficolta: "facile", parcheggio: "comodo in zona", walk: "0-3 min", strada: "asfaltata" },
      crowd: { best: "tardo pomeriggio", worst: "metà giornata in alta stagione" },
      smartTips: [
        "Più da chiusura di giornata che da stop centrale.",
        "Se il cielo si accende verso il tramonto, resta.",
        "Facilissimo da incastrare in un road day nord-ovest."
      ],
      image: "https://picsum.photos/seed/Porto-Moniz-Madeira/900/600"
    },

    {
      id: "core-7",
      name: "Cabo Girão",
      zone: "sud",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "core",
      priority: 9,
      lat: 32.6558,
      lon: -17.0048,
      tags: ["sea cliff", "viewpoint", "tramonto rapido", "sunset", "wow", "grande panorama facile", "skywalk"],
      alias: ["cabo girao", "capo girao", "highest sea cliff europe"],
      desc: "Una delle falesie più alte d'Europa. Vista amplissima sul sud di Madeira.",
      tip: "Vai verso sera. Con luce dura perde parecchio. Stop breve ma fortissimo.",
      longDescription: "Spot immediato, accessibile e forte. Se vuoi grande panorama senza fatica, è una scelta molto solida. Va preso nel momento giusto, non buttato a caso in pieno giorno.",
      photoTips: "Meglio tardo pomeriggio con luce più morbida. Cerca profondità e rapporto costa-mare.",
      experience: { wow: 8, tipo: "viewpoint verticale", tempo: "20-40 min", mood: "grande panorama facile" },
      whenToGo: { best: "tramonto", note: "Luce morbida e atmosfera più bella." },
      whenToAvoid: ["mezzogiorno", "momenti molto affollati"],
      access: { difficolta: "facile", parcheggio: "diretto", walk: "1 min", strada: "asfaltata" },
      crowd: { best: "tardo pomeriggio", worst: "fasce turistiche di metà giornata" },
      smartTips: [
        "Più wow rapido che esperienza lunga: non dargli troppo tempo.",
        "Perfetto da abbinare a Câmara de Lobos o Ponta do Sol.",
        "Anche con copertura parziale regge bene."
      ],
      image: "https://picsum.photos/seed/Cabo-Girao-Madeira/900/600"
    },

    {
      id: "core-8",
      name: "Bica da Cana",
      zone: "ovest",
      light: "alba",
      activity: "view",
      difficulty: "facile",
      level: "core",
      priority: 9,
      lat: 32.7781,
      lon: -17.1128,
      tags: ["sunrise", "easy sunrise", "above clouds", "sea of clouds", "piano B arieiro", "wow facile", "mountain view"],
      alias: ["bica cana", "bica da cana sunrise", "paul da serra sunrise"],
      desc: "Uno dei migliori sunrise facili dell'isola. Spesso sopra le nuvole, resa altissima.",
      tip: "Piano B intelligente se Arieiro è scomodo o affollato. Fatica minima, resa massima.",
      longDescription: "Spot intelligentissimo: fatica bassa, resa alta. Se trovi nuvole sotto quota e cielo pulito sopra, diventa uno dei sunrise più forti di Madeira. Da non sottovalutare.",
      photoTips: "Arriva con anticipo e resta un po' dopo il primo momento. La luce migliore arriva spesso subito dopo.",
      experience: { wow: 9, tipo: "sunrise viewpoint quota", tempo: "20-40 min", mood: "wow facile" },
      whenToGo: { best: "alba", note: "Top con nuvole basse sotto quota e cielo aperto sopra." },
      whenToAvoid: ["copertura alta uniforme", "vento forte"],
      access: { difficolta: "facile", parcheggio: "vicino", walk: "5 min", strada: "asfaltata" },
      crowd: { best: "molto presto", worst: "alba affollata" },
      smartTips: [
        "Guarda la quota delle nuvole: lì si gioca tutto.",
        "Ottimo se vuoi un alba seria senza l'impegno di Arieiro.",
        "Abbinalo a Fanal se la giornata è grigia in basso."
      ],
      image: "https://picsum.photos/seed/Bica-da-Cana-Madeira/900/600"
    },

    {
      id: "core-9",
      name: "Ponta do Pargo Lighthouse",
      zone: "ovest",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "core",
      priority: 9,
      lat: 32.812,
      lon: -17.2623,
      tags: ["sunset", "lighthouse", "tramonto forte", "ovest estremo", "affidabile", "tramonto pulito", "wow"],
      alias: ["ponta pargo", "lighthouse pargo", "faro ponta do pargo", "west point madeira"],
      desc: "Uno dei tramonti più affidabili, puliti e forti di Madeira. Punto ovest estremo dell'isola.",
      tip: "Se sei già a ovest e vuoi chiudere bene, qui è difficile sbagliare.",
      longDescription: "Uno dei sunset spot più forti dell'isola: pulito, leggibile, minimale ma molto efficace. Non serve fare nulla di complicato: stai lì, aspetti, guardi.",
      photoTips: "Arriva un po' prima, lavora con composizioni semplici. Non andare via troppo presto.",
      experience: { wow: 9, tipo: "sunset viewpoint", tempo: "30-50 min", mood: "pulito e forte" },
      whenToGo: { best: "tramonto", note: "Arriva già sul posto con almeno 20 minuti di anticipo." },
      whenToAvoid: ["copertura totale verso ovest"],
      access: { difficolta: "facile", parcheggio: "vicino", walk: "1 min", strada: "asfaltata" },
      crowd: { best: "anticipo sul posto", worst: "tramonti perfetti ad alta stagione" },
      smartTips: [
        "Resta fino alla fine vera della luce.",
        "Funziona bene anche con composizioni molto semplici.",
        "Uno dei posti più affidabili per non sbagliare tramonto."
      ],
      image: "https://picsum.photos/seed/Ponta-do-Pargo-Madeira/900/600"
    },

    {
      id: "core-10",
      name: "Seixal Beach",
      zone: "nord",
      light: "alba",
      activity: "view",
      difficulty: "facile",
      level: "core",
      priority: 9,
      lat: 32.8246,
      lon: -17.1082,
      tags: ["volcanic beach", "black sand", "north coast", "sunrise", "contrasto", "forte visivamente", "spiaggia nera"],
      alias: ["seixal", "praia do seixal", "black beach madeira"],
      desc: "Spiaggia nera con montagne verdi dietro. Uno dei contrasti visivi più forti dell'isola.",
      tip: "Molto bella al mattino presto. Funziona bene come stop nel road day del nord.",
      longDescription: "Una delle immagini più forti del lato nord: sabbia scura, verde intenso e mare. Non è solo fotogenica, è proprio bella da vivere dal vivo.",
      photoTips: "Mattina presto o cielo drammatico. Composizioni larghe e linee della spiaggia rendono molto bene.",
      experience: { wow: 8, tipo: "spiaggia vulcanica", tempo: "30-60 min", mood: "forte contrasto" },
      whenToGo: { best: "alba", note: "Molto valida anche poco dopo." },
      whenToAvoid: ["mezzogiorno piatto", "giornate spente senza luce"],
      access: { difficolta: "facile", parcheggio: "vicino", walk: "2 min", strada: "asfaltata" },
      crowd: { best: "presto", worst: "fasce comode" },
      smartTips: [
        "Ottima in combo con Ribeira da Janela e Porto Moniz.",
        "Rende più dal vivo di quanto sembri in foto.",
        "Funziona bene anche come stop breve ma forte nel nord."
      ],
      image: "https://picsum.photos/seed/Seixal-Beach-Madeira/900/600"
    },

    {
      id: "core-11",
      name: "Eira do Serrado",
      zone: "montagna",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "core",
      priority: 9,
      lat: 32.704,
      lon: -16.9697,
      tags: ["valley view", "curral das freiras", "tramonto", "interno isola", "mountain viewpoint", "facile bello", "panorama interno"],
      alias: ["eira serrado", "serrado", "curral view", "nun's valley viewpoint"],
      desc: "Belvedere forte sulla valle di Curral das Freiras. Interno dell'isola, luce radente bellissima.",
      tip: "Molto bene nel tardo pomeriggio. Senza fatica, resa altissima.",
      longDescription: "Uno dei punti più semplici e forti per leggere l'interno di Madeira. Non richiede fatica vera ma dà una sensazione di profondità e montagna molto bella.",
      photoTips: "Luce radente, ombre sulla valle, forme interne ben leggibili.",
      experience: { wow: 8, tipo: "view sulla valle", tempo: "20-40 min", mood: "panorama interno" },
      whenToGo: { best: "tramonto", note: "La luce radente migliora moltissimo la resa." },
      whenToAvoid: ["meteo chiuso in quota", "visibilità molto scarsa"],
      access: { difficolta: "facile", parcheggio: "vicino", walk: "2 min", strada: "asfaltata" },
      crowd: { best: "tardo pomeriggio", worst: "orari turistici centrali" },
      smartTips: [
        "Perfetto se vuoi montagna vera senza fatica.",
        "Abbinalo a Boca dos Namorados o a Curral das Freiras sotto.",
        "Funziona molto meglio con luce laterale che piatta."
      ],
      image: "https://picsum.photos/seed/Eira-do-Serrado-Madeira/900/600"
    },

    {
      id: "core-12",
      name: "Levada do Caldeirão Verde",
      zone: "nord",
      light: "giorno",
      activity: "trekking",
      difficulty: "medio",
      level: "core",
      priority: 9,
      lat: 32.8072,
      lon: -16.905,
      tags: ["levada", "forest", "waterfall", "green", "immersivo", "levada trekking", "tunnels", "classic madeira"],
      alias: ["caldeirao verde", "caldeirão verde", "levada caldeirao"],
      desc: "Uno dei trekking levada più famosi di Madeira. Verde intenso, tunnel e immersione totale.",
      tip: "Parti presto. Non pensarlo come spot veloce: è una giornata di cammino.",
      longDescription: "Classica esperienza Madeira: vegetazione intensa, percorso bello da vivere, senso di immersione totale nel verde. Non va pensato come stop veloce ma come giornata dedicata.",
      photoTips: "Lavora sulle texture del verde, sui tunnel e sulle prospettive del sentiero, non solo sulla cascata finale.",
      experience: { wow: 8, tipo: "levada trekking", tempo: "3-4h", mood: "immersivo" },
      whenToGo: { best: "mattina", note: "Molto meglio partire presto." },
      whenToAvoid: ["ore tarde", "giorni molto affollati"],
      access: { difficolta: "medio", parcheggio: "facile in zona partenza", walk: "0 min", strada: "asfaltata" },
      crowd: { best: "presto mattina", worst: "metà mattina nei mesi caldi" },
      smartTips: [
        "Non puntare tutto solo sulla cascata finale: il percorso è già molto bello.",
        "Porta torcia per i tunnel.",
        "Meglio farlo quando hai energie vere: non come coda di giornata pesante."
      ],
      image: "https://picsum.photos/seed/Caldeirao-Verde-Madeira/900/600"
    },

    {
      id: "core-13",
      name: "Achadas da Cruz View",
      zone: "nord",
      light: "tramonto",
      activity: "view",
      difficulty: "medio",
      level: "core",
      priority: 9,
      lat: 32.8648,
      lon: -17.2176,
      tags: ["cliff", "sea cliffs", "dramatic", "tramonto", "nord ovest", "verticale", "wow", "esperienza forte"],
      alias: ["achadas da cruz", "achadas cliffs", "cable car madeira"],
      desc: "Una delle scogliere più spettacolari dell'isola. Luce bassa la rende drammatica.",
      tip: "Anche restando solo in alto vale davvero tanto. Non serve scendere.",
      longDescription: "La sensazione forte è la verticalità. È una tappa molto potente visivamente e molto diversa da spot più facili o turistici. Da tenere alta in classifica.",
      photoTips: "Luce bassa e aria pulita. Anche il punto alto da solo regge molto bene.",
      experience: { wow: 9, tipo: "cliff viewpoint", tempo: "30-60 min", mood: "drammatico" },
      whenToGo: { best: "tramonto", note: "Molto forte con aria pulita e luce radente." },
      whenToAvoid: ["meteo chiuso", "vento troppo forte"],
      access: { difficolta: "medio", parcheggio: "facile", walk: "5 min", strada: "asfaltata" },
      crowd: { best: "tardo pomeriggio", worst: "meno critico di altri spot celebri" },
      smartTips: [
        "Da considerare come spot serio, non solo bonus.",
        "Ottimo con Porto Moniz o il lato ovest estremo.",
        "Anche senza scendere con la teleferica, il punto alto vale."
      ],
      image: "https://picsum.photos/seed/Achadas-da-Cruz-View-Madeira/900/600"
    },

    {
      id: "core-14",
      name: "Câmara de Lobos",
      zone: "sud",
      light: "tramonto",
      activity: "relax",
      difficulty: "facile",
      level: "core",
      priority: 9,
      lat: 32.6488,
      lon: -16.9777,
      tags: ["fishing village", "village", "tramonto", "relax", "atmosphere", "porto", "chiusura giornata", "churchill"],
      alias: ["camara de lobos", "camara lobos", "fishing village madeira"],
      desc: "Villaggio di pescatori scenografico e autentico. Perfetto per tramonto, passeggiata e chiusura giornata.",
      tip: "Non solo uno spot da scattare: è un posto da vivere. Fermati, siediti, guarda.",
      longDescription: "Non è il classico wow naturale, ma ha atmosfera vera. Unisce bellezza, semplicità e piacere della serata. Uno di quei posti che funzionano perché sono reali.",
      photoTips: "Luce calda sulle barche, scene semplici, dettagli del porto e del paese.",
      experience: { wow: 7, tipo: "villaggio costiero", tempo: "1-2h", mood: "rilassato" },
      whenToGo: { best: "tramonto", note: "Chiusura semplice ma di qualità." },
      whenToAvoid: ["ore centrali se cerchi atmosfera", "parcheggio scomodo nei momenti pieni"],
      access: { difficolta: "facile", parcheggio: "medio", walk: "5-10 min", strada: "asfaltata" },
      crowd: { best: "tardo pomeriggio", worst: "cena e weekend estivi" },
      smartTips: [
        "Più da vivere che da spuntare e andare via.",
        "Ottimo da combinare con Cabo Girão.",
        "Se hai fame, il pesce qui è concreto."
      ],
      image: "https://picsum.photos/seed/Camara-de-Lobos-Madeira/900/600"
    },

    // ═══ SECONDARY ═════════════════════════════════════════════════════════════

    {
      id: "secondary-0",
      name: "Ponta do Sol",
      zone: "sud",
      light: "tramonto",
      activity: "relax",
      difficulty: "facile",
      level: "secondary",
      priority: 7,
      lat: 32.679,
      lon: -17.1012,
      tags: ["village", "tramonto", "relax", "sud", "piacevole", "chiusura giornata"],
      alias: ["ponta do sol", "sun point madeira"],
      desc: "Paese piacevole sul sud, perfetto per una fine giornata semplice e soddisfacente.",
      tip: "Ideale come chiusura senza stress. Bella atmosfera di sera.",
      longDescription: "Un paese costiero del lato sud con atmosfera genuina. Non è uno spot da grande wow, ma regala una chiusura di giornata bella e tranquilla, soprattutto con luce serale.",
      photoTips: "Luce calda serale sul paese e sul mare. Composizioni semplici funzionano meglio.",
      experience: { wow: 7, tipo: "paese costiero", tempo: "45-90 min", mood: "relax" },
      whenToGo: { best: "tramonto", note: "Luce serale sul paese molto bella." },
      whenToAvoid: ["metà giornata", "attese troppo lunghe in alta stagione"],
      access: { difficolta: "facile", parcheggio: "discreto in zona", walk: "5 min", strada: "asfaltata" },
      crowd: { best: "tardo pomeriggio feriali", worst: "weekend estivi" },
      smartTips: [
        "Molto meglio se ti fermi davvero invece di fare solo una foto.",
        "Ottima in combo con Cabo Girão o Jardim do Mar.",
        "Il lungomare serale vale la sosta."
      ],
      image: "https://picsum.photos/seed/Ponta-do-Sol-Madeira/900/600"
    },

    {
      id: "secondary-1",
      name: "25 Fontes",
      zone: "ovest",
      light: "giorno",
      activity: "trekking",
      difficulty: "medio",
      level: "secondary",
      priority: 7,
      lat: 32.7524,
      lon: -17.1318,
      tags: ["levada", "waterfall", "forest", "classic trail", "affollato", "verde"],
      alias: ["vinte e cinco fontes", "twenty five springs", "levada 25 fontes"],
      desc: "Trekking levada celebre con cascata finale. Bello, ma sensibile all'affollamento.",
      tip: "Parti presto o molto presto se vuoi godertelo davvero.",
      longDescription: "Uno dei percorsi levada più conosciuti dell'isola. Il verde è bello, la cascata è soddisfacente, ma la folla nelle ore centrali può rovinare l'esperienza. Gestisci l'orario con attenzione.",
      photoTips: "Meglio mattina presto con luce più fresca e meno gente. La cascata finale vale la composizione.",
      experience: { wow: 7, tipo: "levada con cascata", tempo: "2-3h", mood: "immersivo" },
      whenToGo: { best: "mattina presto", note: "Folla gestibile solo con partenza precocissima." },
      whenToAvoid: ["metà mattina e pomeriggio in alta stagione"],
      access: { difficolta: "medio", parcheggio: "area base Rabaçal", walk: "partenza diretta", strada: "asfaltata" },
      crowd: { best: "primissima mattina", worst: "metà mattina estate" },
      smartTips: [
        "Non aspettarti solitudine: è uno dei più frequentati.",
        "Il percorso in sé è bello: non correre solo verso la cascata.",
        "Abbinalo a Levada do Risco per completare la zona."
      ],
      image: "https://picsum.photos/seed/25-Fontes-Madeira/900/600"
    },

    {
      id: "secondary-2",
      name: "Levada do Rei",
      zone: "montagna",
      light: "giorno",
      activity: "trekking",
      difficulty: "medio",
      level: "secondary",
      priority: 7,
      lat: 32.8068,
      lon: -16.9075,
      tags: ["levada", "forest", "green", "tranquillo", "meno mainstream", "classic madeira"],
      alias: ["levada rei", "king levada"],
      desc: "Levada solida, verde e appagante. Meno affollata di altre, molto ben bilanciata.",
      tip: "Ottima se vuoi il trekking classico Madeira senza la folla dei soliti percorsi.",
      longDescription: "Un percorso levada che offre la vera essenza di Madeira senza il caos dei classici più celebri. Verde intenso, ritmo piacevole, atmosfera autentica.",
      photoTips: "Linee del canale, verde denso, luci filtrate dalla vegetazione. Mattina presto per la luce migliore.",
      experience: { wow: 7, tipo: "levada trekking", tempo: "2-3h", mood: "immersivo" },
      whenToGo: { best: "mattina", note: "Come quasi tutti i percorsi: prima è meglio." },
      whenToAvoid: ["ore tarde", "pioggia forte"],
      access: { difficolta: "medio", parcheggio: "facile in zona partenza", walk: "breve", strada: "asfaltata" },
      crowd: { best: "qualsiasi orario fuori picco", worst: "weekend alta stagione" },
      smartTips: [
        "Molto più tranquilla di 25 Fontes o Caldeirão Verde.",
        "Ottima scelta se vuoi verde e silenzio senza rinunciare alla qualità.",
        "Facile da inserire in una mezza giornata."
      ],
      image: "https://picsum.photos/seed/Levada-do-Rei-Madeira/900/600"
    },

    {
      id: "secondary-3",
      name: "Balcões",
      zone: "montagna",
      light: "giorno",
      activity: "view",
      difficulty: "facile",
      level: "secondary",
      priority: 7,
      lat: 32.7368,
      lon: -16.897,
      tags: ["viewpoint", "easy walk", "mountain", "panorama", "facile bello", "rapido"],
      alias: ["balcoes viewpoint", "balcões"],
      desc: "Belvedere con rapporto resa-sforzo altissimo. Breve camminata, grande panorama.",
      tip: "Perfetto se vuoi una mattina facile ma bella senza impegno fisico serio.",
      longDescription: "Uno degli spot con il miglior rapporto tra fatica e resa dell'isola. La camminata è breve, il panorama sulla catena montuosa è ampio e soddisfacente.",
      photoTips: "Panorama largo in orizzontale. Funziona bene con nuvole alte e luce laterale.",
      experience: { wow: 7, tipo: "viewpoint facile", tempo: "1-2h", mood: "panorama" },
      whenToGo: { best: "mattina", note: "Nuvole alte possono tagliare la vista: scegli giornate chiare." },
      whenToAvoid: ["copertura alta uniforme", "nebbia densa"],
      access: { difficolta: "facile", parcheggio: "vicino al punto partenza", walk: "20-30 min andata", strada: "asfaltata" },
      crowd: { best: "mattina presto", worst: "metà mattina weekend" },
      smartTips: [
        "Ottimo come warm-up mattutino prima di qualcosa di più serio.",
        "Breve ma molto soddisfacente: non sottovalutarlo.",
        "Abbinabile a Levada do Rei o Caldeirão Verde."
      ],
      image: "https://picsum.photos/seed/Balcoes-Madeira/900/600"
    },

    {
      id: "secondary-6",
      name: "Miradouro do Guindaste",
      zone: "est",
      light: "alba",
      activity: "view",
      difficulty: "facile",
      level: "secondary",
      priority: 7,
      lat: 32.8217,
      lon: -16.8606,
      tags: ["sunrise", "easy sunrise", "est", "viewpoint", "nord", "costa est"],
      alias: ["guindaste", "miradouro guindaste"],
      desc: "Uno dei viewpoint più puliti e facili del lato est. Ottimo sunrise accessibile.",
      tip: "Alternativa sensata se sei già nel nord-est. Nessun problema di accesso.",
      longDescription: "Viewpoint pulito e diretto sul lato est dell'isola. Non ha il drammatismo di Arieiro o Ruivo, ma per un alba senza stress nel nord-est è una scelta molto solida.",
      photoTips: "Luce bassa mattutina sulla costa. Composizioni semplici funzionano bene.",
      experience: { wow: 7, tipo: "sunrise viewpoint", tempo: "20-40 min", mood: "panorama" },
      whenToGo: { best: "alba", note: "Luce bassa mattutina sulla costa." },
      whenToAvoid: ["copertura uniforme", "meteo chiuso"],
      access: { difficolta: "facile", parcheggio: "vicino", walk: "breve", strada: "asfaltata" },
      crowd: { best: "alba feriale", worst: "alba weekend alta stagione" },
      smartTips: [
        "Non aspettarti uno show da Arieiro, ma è un'alba ben fatta.",
        "Ottimo se sei già in zona nord-est la sera prima.",
        "Abbinabile a Ponta de São Lourenço nella stessa mattina."
      ],
      image: "https://picsum.photos/seed/Guindaste-Madeira/900/600"
    },

    {
      id: "secondary-9",
      name: "Curral das Freiras View",
      zone: "montagna",
      light: "giorno",
      activity: "view",
      difficulty: "facile",
      level: "secondary",
      priority: 7,
      lat: 32.7119,
      lon: -16.9702,
      tags: ["valley", "village", "interno isola", "mountain view", "nun's valley"],
      alias: ["curral das freiras", "nun's valley", "vale das freiras"],
      desc: "Valle chiusa e scenografica, molto rappresentativa dell'interno dell'isola.",
      tip: "Funziona bene anche con meteo non perfetto. Il paese giù vale una sosta.",
      longDescription: "Una delle valli più particolari di Madeira: circondata da monti altissimi, con un piccolo paese che sembra fuori dal tempo. Molto rappresentativa dell'interno dell'isola.",
      photoTips: "Mattino con nuvole che si aprono è il momento migliore. La prospettiva dal bordo è già molto forte.",
      experience: { wow: 7, tipo: "valley view", tempo: "30-60 min", mood: "panorama interno" },
      whenToGo: { best: "giorno", note: "Meglio al mattino con nuvole ancora basse che si aprono." },
      whenToAvoid: ["nebbia densa", "visibilità zero"],
      access: { difficolta: "facile", parcheggio: "vicino al belvedere", walk: "2 min", strada: "asfaltata" },
      crowd: { best: "mattina presto", worst: "turisti di mezzogiorno" },
      smartTips: [
        "Abbinalo a Eira do Serrado per il meglio delle valli interne.",
        "Il paese sotto vale una discesa se hai il tempo.",
        "Molto utile come tappa nel percorso tra Funchal e ovest."
      ],
      image: "https://picsum.photos/seed/Curral-das-Freiras-Madeira/900/600"
    },

    {
      id: "secondary-11",
      name: "Paul da Serra",
      zone: "ovest",
      light: "tramonto",
      activity: "mtb",
      difficulty: "medio",
      level: "secondary",
      priority: 6,
      lat: 32.763,
      lon: -17.133,
      tags: ["plateau", "open sky", "MTB", "tramonto", "wind turbines", "paesaggio aperto", "spazio"],
      alias: ["paul da serra", "paul serra plateau"],
      desc: "Altipiano aperto e ventoso sopra l'ovest. Più atmosfera e spazio che spot singolo.",
      tip: "Bellissimo con luce lunga e orizzonte largo. Ottimo per MTB su asfalto aperto.",
      longDescription: "Un plateau unico nel suo genere a Madeira: aperto, ampio, ventoso. Dà una sensazione di libertà molto diversa dal resto dell'isola. Meglio con luce radente e visibilità buona.",
      photoTips: "Spazio aperto e turbine eoliche con luce radente. Composizioni minimali funzionano benissimo.",
      experience: { wow: 7, tipo: "altipiano aperto", tempo: "1-3h", mood: "spazio" },
      whenToGo: { best: "tramonto", note: "Luce radente e colori caldi sul plateau." },
      whenToAvoid: ["nebbia densa senza luce"],
      access: { difficolta: "medio", parcheggio: "area plateau", walk: "n/a", strada: "asfalto e sterrati aperti" },
      crowd: { best: "feriali", worst: "giorni perfetti molto frequentati" },
      smartTips: [
        "Perfetto come modulo MTB nel lato ovest.",
        "Anche solo in auto vale la sosta per l'atmosfera.",
        "Nebbia fitta lo penalizza molto: tienilo per le giornate aperte."
      ],
      image: "https://picsum.photos/seed/Paul-da-Serra-Madeira/900/600"
    },

    {
      id: "secondary-15",
      name: "Garajau Cristo Rei",
      zone: "sud",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "secondary",
      priority: 6,
      lat: 32.6372,
      lon: -16.8501,
      tags: ["sunset", "cliff", "statua", "tramonto", "est funchal", "viewpoint"],
      alias: ["garajau", "cristo rei madeira"],
      desc: "Scogliera con statua sul mare, molto valida verso sera. Vicina a Funchal.",
      tip: "Bel tramonto semplice senza grossi spostamenti dal centro.",
      longDescription: "Comodo da raggiungere da Funchal, offre un tramonto decente con vista sul mare. La statua dà un elemento visivo diverso dagli altri spot di Madeira.",
      photoTips: "Statua in controluce al tramonto. Vista sulla costa est con luce radente.",
      experience: { wow: 7, tipo: "viewpoint costiero", tempo: "20-40 min", mood: "tramonto" },
      whenToGo: { best: "tramonto", note: "Luce serale sulla costa est." },
      whenToAvoid: ["metà giornata", "copertura uniforme verso ovest"],
      access: { difficolta: "facile", parcheggio: "comodo", walk: "5 min", strada: "asfaltata" },
      crowd: { best: "tardo pomeriggio", worst: "orari turistici centrali" },
      smartTips: [
        "Ottimo come primo tramonto se sei appena arrivato a Funchal.",
        "Facile da abbinare a una cena in città.",
        "Non aspettarti qualcosa di straordinario, ma è un tramonto valido."
      ],
      image: "https://picsum.photos/seed/Garajau-Cristo-Rei-Madeira/900/600"
    },

    {
      id: "secondary-17",
      name: "Pico dos Barcelos",
      zone: "sud",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "secondary",
      priority: 7,
      lat: 32.6656,
      lon: -16.9372,
      tags: ["sunset", "viewpoint", "funchal view", "tramonto facile", "vicino città", "easy sunset"],
      alias: ["barcelos", "pico barcelos", "miradouro barcelos"],
      desc: "Belvedere accessibile con vista ampia su Funchal. Soluzione easy ma forte vicino alla città.",
      tip: "Ottimo se vuoi tramonto di qualità senza allontanarti da Funchal.",
      longDescription: "Uno dei viewpoint più accessibili vicino a Funchal. Vista ampia sulla città e sul mare. Non è uno spot selvaggio, ma per una serata senza spostamenti è molto valido.",
      photoTips: "Vista su Funchal illuminata dalla luce serale. Composizioni ampie con la città in basso.",
      experience: { wow: 7, tipo: "sunset viewpoint", tempo: "20-40 min", mood: "tramonto" },
      whenToGo: { best: "tramonto", note: "Vista su Funchal illuminata dalla luce serale." },
      whenToAvoid: ["copertura totale", "mezzogiorno"],
      access: { difficolta: "facile", parcheggio: "discreto", walk: "breve", strada: "asfaltata" },
      crowd: { best: "tardo pomeriggio", worst: "turisti del centro in serata" },
      smartTips: [
        "Perfetto per chi alloggia a Funchal e vuole un tramonto facile.",
        "Ottimo come prima serata di ambientamento.",
        "Abbinalo a una cena in centro per chiudere bene."
      ],
      image: "https://picsum.photos/seed/Pico-dos-Barcelos-Madeira/900/600"
    },

    {
      id: "secondary-18",
      name: "Miradouro do Pináculo",
      zone: "sud",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "secondary",
      priority: 6,
      lat: 32.6555,
      lon: -16.8794,
      tags: ["sunset", "viewpoint", "funchal", "tramonto rapido", "est funchal", "view"],
      alias: ["pinaculo", "miradouro pinaculo"],
      desc: "Vista alta sulla città e sul lato est di Funchal. Molto valido in luce serale.",
      tip: "Valida alternativa a Barcelos se sei dal lato est.",
      longDescription: "Viewpoint alternativo a Barcelos per chi si trova dal lato est di Funchal. Vista ampia sulla città e sulla costa. Semplice, accessibile, efficace.",
      photoTips: "Vista sulla città con luce serale. Simile a Barcelos ma con angolo leggermente diverso.",
      experience: { wow: 7, tipo: "viewpoint sunset", tempo: "20-40 min", mood: "tramonto" },
      whenToGo: { best: "tramonto", note: "Luce serale sulla città." },
      whenToAvoid: ["metà giornata", "copertura fitta"],
      access: { difficolta: "facile", parcheggio: "comodo", walk: "breve", strada: "asfaltata" },
      crowd: { best: "tardo pomeriggio", worst: "orari turistici peak" },
      smartTips: [
        "Alternativa smart a Barcelos se sei già sul lato est.",
        "Non stai perdendo nulla scegliendo questo rispetto a Barcelos.",
        "Rapido e soddisfacente come stop serale."
      ],
      image: "https://picsum.photos/seed/Pinaculo-Madeira/900/600"
    },

    {
      id: "secondary-19",
      name: "Miradouro da Portela",
      zone: "montagna",
      light: "giorno",
      activity: "view",
      difficulty: "facile",
      level: "secondary",
      priority: 6,
      lat: 32.7399,
      lon: -16.8297,
      tags: ["viewpoint", "nord-est", "panorama", "tappa passaggio", "mountain"],
      alias: ["portela", "portela viewpoint"],
      desc: "Belvedere leggibile su costa e rilievi del nord-est. Ottima tappa di passaggio.",
      tip: "Ottima tappa di passaggio ben spesa. Nessuno sforzo, buona resa.",
      longDescription: "Un viewpoint ben posizionato sulla strada che attraversa il nord-est dell'isola. Vista pulita su costa e montagna. Ideale come pausa durante un road day.",
      photoTips: "Vista sulla costa nord-est e sulle montagne. Meglio con luce laterale mattutina.",
      experience: { wow: 6, tipo: "viewpoint", tempo: "15-30 min", mood: "panorama" },
      whenToGo: { best: "mattina", note: "Luce laterale e nuvole basse che si aprono." },
      whenToAvoid: ["nebbia chiusa", "visibilità zero"],
      access: { difficolta: "facile", parcheggio: "vicino", walk: "2 min", strada: "asfaltata" },
      crowd: { best: "fuori dagli orari turistici", worst: "orari bus turistici" },
      smartTips: [
        "Non deviare apposta: usalo come stop naturale durante uno spostamento.",
        "Vale 15 minuti, non di più.",
        "Ottimo break nel road day del nord-est."
      ],
      image: "https://picsum.photos/seed/Portela-Madeira/900/600"
    },

    {
      id: "secondary-21",
      name: "Rocha do Navio",
      zone: "nord",
      light: "giorno",
      activity: "view",
      difficulty: "medio",
      level: "secondary",
      priority: 6,
      lat: 32.8164,
      lon: -16.885,
      tags: ["cliff", "cable car", "north coast", "scenico", "alternativo", "telecabina"],
      alias: ["rocha navio", "rocha do navio", "cable car north madeira"],
      desc: "Scogliera e teleferica nel nord. Molto scenica e diversa dagli altri spot.",
      tip: "Molto valida come tappa nord se vuoi qualcosa di diverso dai classici.",
      longDescription: "Una delle tappe nord più particolari: una teleferica storica scende verso il mare tra scogliere. L'esperienza è unica nel suo genere e molto diversa dai soliti viewpoint.",
      photoTips: "La teleferica e la scogliera insieme danno composizioni molto originali. Funziona bene con luce laterale.",
      experience: { wow: 7, tipo: "cliff e teleferica", tempo: "30-60 min", mood: "scenico" },
      whenToGo: { best: "mattina", note: "Luce laterale sul nord." },
      whenToAvoid: ["giornate chiuse", "vento forte che blocca la teleferica"],
      access: { difficolta: "medio", parcheggio: "comodo", walk: "breve", strada: "asfaltata" },
      crowd: { best: "feriali", worst: "weekend con turisti" },
      smartTips: [
        "L'unicità della teleferica è il vero valore aggiunto.",
        "Controlla che la teleferica sia operativa prima di andare.",
        "Ottimo in combo con la costa nord tra Faial e Ribeira da Janela."
      ],
      image: "https://picsum.photos/seed/Rocha-do-Navio-Madeira/900/600"
    },

    {
      id: "secondary-22",
      name: "Paul do Mar",
      zone: "sud",
      light: "tramonto",
      activity: "relax",
      difficulty: "facile",
      level: "secondary",
      priority: 7,
      lat: 32.7605,
      lon: -17.2291,
      tags: ["village", "tramonto", "surf", "ovest", "carattere", "chiusura giornata"],
      alias: ["paul do mar", "paul mar"],
      desc: "Costa ruvida e carattere vero nel lato ovest estremo. Buona come chiusura con stile.",
      tip: "Atmosfera molto buona a fine giornata. Posto con carattere.",
      longDescription: "Un paese con identità propria nell'estremo ovest dell'isola. Meno patinato e più autentico di altri posti. La costa è ruvida, il mare è presente, l'atmosfera è quella di un posto vero.",
      photoTips: "Atmosfera autentica del paese, costa rocciosa, luce serale. Più fotografia di strada che paesaggio classico.",
      experience: { wow: 7, tipo: "paese costiero ovest", tempo: "30-60 min", mood: "relax" },
      whenToGo: { best: "tramonto", note: "Luce serale e atmosfera autentici." },
      whenToAvoid: ["metà giornata senza atmosfera"],
      access: { difficolta: "facile", parcheggio: "comodo in paese", walk: "5 min", strada: "asfaltata" },
      crowd: { best: "feriali serali", worst: "weekend estivi" },
      smartTips: [
        "Meglio abbinarlo alla versione surf se vuoi più contenuto.",
        "L'autenticità è il suo punto forte: non aspettarti servizi turistici.",
        "Ottima chiusura per un road day sull'ovest."
      ],
      image: "https://picsum.photos/seed/Paul-do-Mar-Madeira/900/600"
    },

    {
      id: "secondary-23",
      name: "Jardim do Mar View",
      zone: "sud",
      light: "tramonto",
      activity: "view",
      difficulty: "facile",
      level: "secondary",
      priority: 7,
      lat: 32.739,
      lon: -17.212,
      tags: ["village", "sunset", "ovest", "tramonto", "piacevole", "chiusura"],
      alias: ["jardim do mar", "jardim mar"],
      desc: "Paesino sul lato ovest con costa molto piacevole verso sera.",
      tip: "Molto valido per una chiusura semplice. Carattere vero.",
      longDescription: "Un piccolo borgo costiero con una posizione bellissima verso ovest. Il tramonto da qui è pulito e la vicinanza all'oceano dà un'atmosfera unica.",
      photoTips: "Costa e paese in luce serale. Vista sull'oceano aperto verso ovest.",
      experience: { wow: 7, tipo: "paese e costa", tempo: "30-60 min", mood: "tramonto" },
      whenToGo: { best: "tramonto", note: "Luce serale e paese tranquillo." },
      whenToAvoid: ["copertura fitta verso ovest"],
      access: { difficolta: "facile", parcheggio: "comodo in paese", walk: "5 min", strada: "asfaltata" },
      crowd: { best: "tardo pomeriggio feriali", worst: "weekend estivi" },
      smartTips: [
        "Abbinalo a Paul do Mar per chiudere bene il lato ovest.",
        "Molto più tranquillo di molti altri spot tramonto.",
        "L'oceano aperto verso ovest è il vero protagonista."
      ],
      image: "https://picsum.photos/seed/Jardim-do-Mar-View-Madeira/900/600"
    },

    {
      id: "secondary-24",
      name: "Levada do Risco",
      zone: "ovest",
      light: "giorno",
      activity: "trekking",
      difficulty: "facile",
      level: "secondary",
      priority: 6,
      lat: 32.7528,
      lon: -17.1321,
      tags: ["levada", "waterfall", "facile", "forest", "verde", "ovest"],
      alias: ["risco", "levada risco", "cascata risco"],
      desc: "Percorso breve verso una cascata scenica. Facile da infilare in giornata.",
      tip: "Molto facile da includere. Buon rapporto sforzo-resa.",
      longDescription: "Un percorso levada corto ma soddisfacente che porta a una cascata bella. Ottimo se vuoi aggiungere un elemento naturale senza impegno fisico vero.",
      photoTips: "La cascata finale è il soggetto principale. Funziona bene con luce diffusa o leggermente nuvoloso.",
      experience: { wow: 7, tipo: "levada breve con cascata", tempo: "1-2h", mood: "immersivo" },
      whenToGo: { best: "mattina", note: "Luce più fresca e meno gente." },
      whenToAvoid: ["pioggia forte", "fango sul sentiero"],
      access: { difficolta: "facile", parcheggio: "area Rabaçal", walk: "partenza breve", strada: "asfaltata" },
      crowd: { best: "mattina presto", worst: "metà giornata alta stagione" },
      smartTips: [
        "Ottima in combo con 25 Fontes nella stessa mattina.",
        "Non aspettarti un trekking impegnativo: è una passeggiata.",
        "La cascata finale è davvero bella anche se il percorso è corto."
      ],
      image: "https://picsum.photos/seed/Risco-Madeira/900/600"
    },

    // ═══ SPORT (secondary) ══════════════════════════════════════════════════════

    {
      id: "sport-0",
      name: "Vereda do Larano",
      zone: "est",
      light: "giorno",
      activity: "trekking",
      difficulty: "medio",
      level: "secondary",
      priority: 8,
      lat: 32.7702,
      lon: -16.8424,
      tags: ["coastal hike", "cliff trail", "panoramic", "oceano", "wow", "costa drammatica", "trekking panoramico"],
      alias: ["larano", "vereda do larano", "boca do risco", "porto da cruz machico trail"],
      desc: "Uno dei trekking costieri più forti di Madeira: oceano sotto, scogliera viva e grande sensazione di esposizione.",
      tip: "Da fare con meteo stabile e fondo asciutto. Se il tempo è incerto o il vento è forte, perde molto.",
      longDescription: "Un percorso costiero che mette bene in mostra il lato est dell'isola. Oceano sotto, creste, sensazione di esposizione vera. Uno dei trekking più appaganti fuori dai classici.",
      weatherNote: "Con pioggia, raffiche o scarsa visibilità la parte esposta diventa meno piacevole e meno leggibile.",
      photoTips: "Molto forte con luce laterale e mare ben leggibile sotto. Le linee della costa fanno già il lavoro.",
      experience: { wow: 9, tipo: "trekking costiero panoramico", tempo: "3-5h", mood: "epico" },
      whenToGo: { best: "giorno", note: "Meglio con cielo pulito, vento contenuto e buona visibilità sulla costa est." },
      whenToAvoid: ["vento forte", "pioggia", "meteo instabile", "fondo scivoloso"],
      access: { difficolta: "medio", parcheggio: "variabile tra Machico e Porto da Cruz", walk: "partenza diretta", strada: "asfaltata ai punti base" },
      crowd: { best: "feriali o partenza presto", worst: "giorni molto belli nel weekend" },
      smartTips: [
        "Più esperienza lineare che viewpoint statico.",
        "Ottimo se vuoi una Madeira più sportiva ma ancora visivamente fortissima.",
        "Non sprecarlo con meteo mediocre."
      ],
      image: "https://picsum.photos/seed/Larano-Madeira/900/600"
    },

    {
      id: "sport-1",
      name: "Levada do Alecrim",
      zone: "ovest",
      light: "giorno",
      activity: "trekking",
      difficulty: "facile",
      level: "secondary",
      priority: 7,
      lat: 32.7582,
      lon: -17.1371,
      tags: ["levada", "waterfall", "green", "immersivo", "rabaçal", "laurisilva", "trekking easy"],
      alias: ["alecrim", "levada do alecrim", "pr 6.2", "rabaçal alecrim"],
      desc: "Levada molto riuscita nell'area del Rabaçal: verde, acqua, tunnel naturali e grande atmosfera senza essere pesante.",
      tip: "Molto buona se vuoi un trekking completo ma più morbido rispetto ai percorsi più battuti o faticosi.",
      longDescription: "Un percorso levada che dà il meglio dell'area Rabaçal senza la pressione dei percorsi più affollati. Verde denso, atmosfera bella, ritmo piacevole.",
      weatherNote: "Regge bene anche con cielo grigio leggero. Con pioggia vera diventa meno piacevole.",
      photoTips: "Più che cercare la singola foto, lavora sulle linee della levada, il verde e la profondità del bosco.",
      experience: { wow: 8, tipo: "levada trekking facile", tempo: "2-3h", mood: "immersivo" },
      whenToGo: { best: "mattina", note: "Partire presto migliora tranquillità, ritmo e qualità generale del percorso." },
      whenToAvoid: ["pioggia forte", "metà giornata nei giorni più pieni"],
      access: { difficolta: "facile", parcheggio: "area Rabaçal", walk: "partenza breve", strada: "asfaltata fino all'area base" },
      crowd: { best: "presto mattina", worst: "fasce centrali con traffico Rabaçal" },
      smartTips: [
        "Scelta intelligente se vuoi natura vera senza giornata pesante.",
        "Più uniforme e meno caotica di altri classici vicini.",
        "Molto buona come modulo trekking di mezza giornata."
      ],
      image: "https://picsum.photos/seed/Alecrim-Madeira/900/600"
    },

    {
      id: "sport-2",
      name: "Lagoa do Vento",
      zone: "ovest",
      light: "giorno",
      activity: "trekking",
      difficulty: "medio",
      level: "secondary",
      priority: 7,
      lat: 32.7569,
      lon: -17.1385,
      tags: ["waterfall", "wild", "rabaçal", "trekking", "cascata", "più selvaggio", "verde"],
      alias: ["lagoa do vento", "vereda da lagoa do vento", "pr 6.3", "rabaçal lagoa"],
      desc: "Percorso più corto ma molto scenografico verso una delle cascate più suggestive dell'area del Rabaçal.",
      tip: "Molto più bello se vuoi qualcosa di più wild e meno standard rispetto ai percorsi levada più classici.",
      longDescription: "Un percorso che porta a una cascata davvero suggestiva in un ambiente molto selvaggio. Più fisico e autentico di una levada classica, con una ricompensa visiva forte.",
      weatherNote: "Con terreno bagnato e pioggia vera il sentiero perde comfort. Molto meglio con finestra stabile.",
      photoTips: "La cascata e l'ambiente attorno funzionano bene con luce morbida e aria umida, non con sole duro.",
      experience: { wow: 8, tipo: "trekking cascata", tempo: "1h30-3h", mood: "avventura" },
      whenToGo: { best: "mattina", note: "Meglio partire presto per avere più calma e una lettura migliore del luogo." },
      whenToAvoid: ["pioggia forte", "fondo molto scivoloso", "metà giornata piena"],
      access: { difficolta: "medio", parcheggio: "area Rabaçal", walk: "partenza breve", strada: "asfaltata fino alla base" },
      crowd: { best: "presto", worst: "ore centrali nei giorni molto richiesti" },
      smartTips: [
        "Più experience spot che semplice cascata.",
        "Ottimo se vuoi acqua e natura con più carattere.",
        "Molto forte in combo con Alecrim o Risco, ma non tutto insieme se vuoi godertelo."
      ],
      image: "https://picsum.photos/seed/Lagoa-do-Vento-Madeira/900/600"
    },

    {
      id: "sport-3",
      name: "Canyoning Ribeiro Bonito",
      zone: "nord",
      light: "giorno",
      activity: "water",
      difficulty: "impegnativo",
      level: "secondary",
      priority: 8,
      lat: 32.8079,
      lon: -16.9038,
      tags: ["canyoning", "water sport", "adrenalina", "waterfall", "esperienza guidata", "natura forte"],
      alias: ["ribeiro bonito", "canyoning ribeiro bonito", "bonito canyon", "madeira canyoning north"],
      desc: "Una delle esperienze canyoning più forti e complete dell'isola: acqua, roccia, verticalità e ambiente molto bello.",
      tip: "Da leggere come esperienza guidata premium, non come spot statico. È uno dei moduli sport più forti che puoi mettere in app.",
      longDescription: "Canyoning serio in un ambiente naturale straordinario. L'acqua, la roccia e la verticalità creano un'esperienza che rimane impressa. Da fare con guida qualificata e condizioni confermate.",
      weatherNote: "Condizioni acqua e sicurezza vanno sempre verificate con guida o operatore. Non trattarlo come uscita improvvisata.",
      photoTips: "Più esperienza che foto: qui conta l'ambiente totale, non il singolo viewpoint.",
      experience: { wow: 10, tipo: "canyoning guidato", tempo: "3-5h", mood: "avventura" },
      whenToGo: { best: "giorno", note: "Molto meglio con condizioni confermate e temperature buone." },
      whenToAvoid: ["meteo instabile", "uscita improvvisata", "condizioni acqua non confermate"],
      access: { difficolta: "impegnativo", parcheggio: "variabile in base al meeting point", walk: "variabile", strada: "asfaltata ai punti base" },
      crowd: { best: "turni mattina o feriali", worst: "giorni top di alta stagione" },
      smartTips: [
        "Uno dei migliori spot sportivi per alzare davvero il livello dell'app.",
        "Molto diverso dai classici trekking: aggiunge varietà vera.",
        "Perfetto come 'esperienza forte' e non solo come luogo."
      ],
      image: "https://picsum.photos/seed/Ribeiro-Bonito-Madeira/900/600"
    },

    {
      id: "sport-4",
      name: "Canyoning Ribeira das Cales",
      zone: "sud",
      light: "giorno",
      activity: "water",
      difficulty: "medio",
      level: "secondary",
      priority: 7,
      lat: 32.6789,
      lon: -16.9068,
      tags: ["canyoning", "water sport", "waterfall", "esperienza guidata", "adrenalina", "entry level"],
      alias: ["ribeira das cales", "canyoning ribeira das cales", "cales canyon"],
      desc: "Modulo canyoning più accessibile ma molto divertente: ottimo per iniziare senza perdere il lato avventura.",
      tip: "Se vuoi inserire un canyoning più facile e credibile nell'app, questo è perfetto come primo step.",
      longDescription: "Una versione entry-level del canyoning madeiran. Meno impegnativo del Ribeiro Bonito ma ugualmente divertente e soddisfacente. Perfetto per chi si avvicina per la prima volta.",
      weatherNote: "Anche qui conta la guida e la verifica delle condizioni reali dell'acqua.",
      photoTips: "Non è uno spot da guardare da fuori: va pensato come esperienza immersiva.",
      experience: { wow: 8, tipo: "canyoning guidato", tempo: "2-4h", mood: "avventura" },
      whenToGo: { best: "giorno", note: "Molto meglio con meteo stabile e gestione guidata." },
      whenToAvoid: ["meteo incerto", "condizioni non confermate", "uscita improvvisata"],
      access: { difficolta: "medio", parcheggio: "variabile in base al ritrovo", walk: "breve", strada: "asfaltata" },
      crowd: { best: "feriali o turni presto", worst: "giorni pieni in alta stagione" },
      smartTips: [
        "Più facile del Ribeiro Bonito ma molto utile in app.",
        "Perfetto per aprire il filtro Acqua a qualcosa di davvero sportivo.",
        "Va raccontato come esperienza, non come viewpoint."
      ],
      image: "https://picsum.photos/seed/Ribeira-das-Cales-Madeira/900/600"
    },

    {
      id: "sport-5",
      name: "Surf Porto da Cruz",
      zone: "est",
      light: "giorno",
      activity: "water",
      difficulty: "medio",
      level: "secondary",
      priority: 7,
      lat: 32.7661,
      lon: -16.8297,
      tags: ["surf", "wave", "ocean", "sport", "east coast", "sea energy"],
      alias: ["surf porto da cruz", "porto da cruz surf", "porto cruz surf"],
      desc: "Uno dei riferimenti surf più conosciuti di Madeira. Spot con identità vera e mare da rispettare.",
      tip: "Molto buono per rendere il filtro Acqua meno turistico e più sportivo. Da leggere sempre con swell e vento.",
      longDescription: "Surf spot con una sua identità precisa nel lato est dell'isola. Non è uno spot da principianti: il mare qui ha carattere e va rispettato. Ottimo per chi conosce l'acqua.",
      weatherNote: "Le condizioni cambiano tutto: vento e mare decidono se ha senso o no.",
      photoTips: "Più che il paesaggio, qui conta l'energia del mare e il timing giusto.",
      experience: { wow: 8, tipo: "surf spot oceanico", tempo: "1-3h", mood: "sport" },
      whenToGo: { best: "giorno", note: "Dipende dalle condizioni del mare più che dall'orario puro." },
      whenToAvoid: ["mare disordinato per il tuo livello", "vento sfavorevole", "condizioni non lette bene"],
      access: { difficolta: "medio", parcheggio: "comodo in zona", walk: "breve", strada: "asfaltata" },
      crowd: { best: "giorni buoni ma non perfetti", worst: "swell forti con spot pieno" },
      smartTips: [
        "Aggiunge sport vero al lato est dell'isola.",
        "Va usato come modulo activity-based, non come semplice sosta mare.",
        "Ottimo se vuoi dare più personalità alla categoria water."
      ],
      image: "https://picsum.photos/seed/Surf-Porto-da-Cruz-Madeira/900/600"
    },

    {
      id: "sport-6",
      name: "Surf Paul do Mar",
      zone: "sud",
      light: "giorno",
      activity: "water",
      difficulty: "medio",
      level: "secondary",
      priority: 7,
      lat: 32.7604,
      lon: -17.2291,
      tags: ["surf", "wave", "ocean", "west side", "sport", "autentico"],
      alias: ["surf paul do mar", "paul do mar surf", "paul surf madeira"],
      desc: "Spot surf più ruvido e autentico del lato ovest. Meno cartolina, più carattere vero.",
      tip: "Perfetto per dare al tuo dataset un modulo oceanico con personalità forte, non da spiaggia comoda.",
      longDescription: "Il lato ovest di Madeira ha un mare con carattere diverso dal resto dell'isola. Questo spot lo rappresenta bene: autentico, ruvido, con un'energia oceanica vera.",
      weatherNote: "Come ogni surf spot, senza lettura mare e vento non ha senso valutarlo davvero.",
      photoTips: "La forza qui è l'atmosfera del posto e l'energia del mare più che il singolo frame pulito.",
      experience: { wow: 9, tipo: "surf spot oceanico", tempo: "1-3h", mood: "sport" },
      whenToGo: { best: "giorno", note: "Va letto sulle condizioni reali del mare, non solo sull'orario." },
      whenToAvoid: ["condizioni troppo forti per il tuo livello", "vento sfavorevole", "mare disordinato"],
      access: { difficolta: "medio", parcheggio: "comodo in paese", walk: "breve", strada: "asfaltata" },
      crowd: { best: "giorni medi o feriali", worst: "condizioni top con spot pieno" },
      smartTips: [
        "Molto più sportivo di un semplice Paul do Mar relax.",
        "Tiene bene il lato ovest e dà profondità al filtro water.",
        "Molto coerente con una Madeira più attiva."
      ],
      image: "https://picsum.photos/seed/Surf-Paul-do-Mar-Madeira/900/600"
    },

    {
      id: "sport-7",
      name: "Coasteering Madeira South",
      zone: "sud",
      light: "giorno",
      activity: "water",
      difficulty: "medio",
      level: "secondary",
      priority: 7,
      lat: 32.6501,
      lon: -16.9499,
      tags: ["coasteering", "adrenalina", "ocean", "salti", "esperienza guidata", "roccia e mare"],
      alias: ["coasteering madeira", "coasteering south madeira", "madeira south coasteering"],
      desc: "Salti, nuoto e roccia sul mare: esperienza completa e molto diversa da kayak o surf.",
      tip: "Molto utile per dare varietà vera alla categoria Acqua. Sempre da leggere come esperienza guidata.",
      longDescription: "Un'esperienza che combina arrampicata, salti e nuoto in mare aperto lungo le scogliere. Molto diversa da qualsiasi altra attività acqua dell'isola. Va gestita con un operatore qualificato.",
      weatherNote: "Condizioni del mare fondamentali. Non è una semplice attività acqua soft.",
      photoTips: "Qui conta l'azione e la sensazione di immersione, non la cartolina.",
      experience: { wow: 9, tipo: "coasteering guidato", tempo: "2-4h", mood: "avventura" },
      whenToGo: { best: "giorno", note: "Ha senso solo con mare leggibile e condizioni confermate." },
      whenToAvoid: ["mare troppo mosso", "uscita improvvisata", "condizioni non confermate"],
      access: { difficolta: "medio", parcheggio: "variabile in base al punto ritrovo", walk: "breve", strada: "asfaltata" },
      crowd: { best: "feriali o turni mattina", worst: "giorni molto pieni" },
      smartTips: [
        "Aggiunge una dimensione molto fresca al filtro water.",
        "Più esperienza che luogo preciso.",
        "Ottimo per chi vuole fare qualcosa di memorabile senza essere solo trekking."
      ],
      image: "https://picsum.photos/seed/Coasteering-Madeira/900/600"
    },

    {
      id: "sport-8",
      name: "Paragliding Arco da Calheta",
      zone: "ovest",
      light: "tramonto",
      activity: "view",
      difficulty: "medio",
      level: "secondary",
      priority: 8,
      lat: 32.7102,
      lon: -17.1798,
      tags: ["paragliding", "air", "view", "oceano", "esperienza guidata", "tramonto"],
      alias: ["paragliding calheta", "arco da calheta paragliding", "parapente calheta"],
      desc: "Esperienza volo molto scenografica sopra il lato ovest, con oceano aperto e resa alta quando l'aria collabora.",
      tip: "Va trattato come esperienza premium e non come semplice viewpoint. Il timing delle condizioni conta tutto.",
      longDescription: "Volare sopra il lato ovest di Madeira con l'oceano sotto è un'esperienza che pochi spot possono eguagliare. Non è per tutti i giorni, ma quando le condizioni ci sono è qualcosa di memorabile.",
      weatherNote: "Vento e condizioni aria sono decisivi. Non inserirlo in planner come fosse uno spot statico facile.",
      photoTips: "L'impatto qui è l'esperienza totale del volo e del paesaggio sotto, più che la singola immagine.",
      experience: { wow: 9, tipo: "parapendio panoramico", tempo: "1h", mood: "epico" },
      whenToGo: { best: "tramonto", note: "Molto bello con luce calda e condizioni aria stabili." },
      whenToAvoid: ["vento sfavorevole", "condizioni aria instabili", "meteo incerto"],
      access: { difficolta: "medio", parcheggio: "variabile in base al decollo/ritrovo", walk: "breve", strada: "asfaltata" },
      crowd: { best: "giorni buoni ma ordinati", worst: "finestre perfette molto richieste" },
      smartTips: [
        "Non complica i filtri ma alza tanto il livello del dataset.",
        "Perfetto come esperienza wow fuori dal solo trekking.",
        "Tienilo come modulo premium, non come filler."
      ],
      image: "https://picsum.photos/seed/Paragliding-Madeira/900/600"
    },

    {
      id: "sport-9",
      name: "Paul da Serra MTB Loop",
      zone: "ovest",
      light: "giorno",
      activity: "mtb",
      difficulty: "medio",
      level: "secondary",
      priority: 6,
      lat: 32.7631,
      lon: -17.1332,
      tags: ["mtb", "open space", "plateau", "paul da serra", "outdoor", "spazio"],
      alias: ["paul da serra mtb", "mtb paul da serra", "paul plateau ride"],
      desc: "Modulo MTB nell'altipiano più aperto dell'isola: spazio, aria e sensazione di terreno ampio e libero.",
      tip: "Molto meglio con visibilità buona. Se c'è nebbia chiusa perde gran parte del suo fascino.",
      longDescription: "Il plateau di Paul da Serra è il posto migliore di Madeira per fare MTB su terreno aperto. Spazio, aria, orizzonti larghi: una sensazione completamente diversa dai trail in quota o in foresta.",
      weatherNote: "Vento e nebbia cambiano completamente la qualità dell'uscita.",
      photoTips: "Più che cercare il punto singolo, qui funziona la sensazione di spazio aperto.",
      experience: { wow: 7, tipo: "MTB plateau ride", tempo: "1-3h", mood: "sport" },
      whenToGo: { best: "giorno", note: "Meglio con meteo pulito e orizzonte leggibile." },
      whenToAvoid: ["nebbia densa", "vento molto forte", "meteo chiuso"],
      access: { difficolta: "medio", parcheggio: "facile in area plateau", walk: "n/a", strada: "asfalto e sterrati aperti" },
      crowd: { best: "feriali", worst: "giorni perfetti molto frequentati" },
      smartTips: [
        "Molto più coerente di un trail running dentro activity MTB.",
        "Ottimo per rafforzare davvero il filtro bici.",
        "Più atmosfera sportiva che singolo wow statico."
      ],
      image: "https://picsum.photos/seed/Paul-da-Serra-MTB-Madeira/900/600"
    },

    // ═══ EXTRA ══════════════════════════════════════════════════════════════════

    {
      id: "extra-0",
      name: "Miradouro do Véu da Noiva",
      zone: "nord",
      light: "giorno",
      activity: "view",
      difficulty: "facile",
      level: "extra",
      priority: 4,
      lat: 32.8335,
      lon: -17.1258,
      tags: ["waterfall", "coastal waterfall", "north", "rapido", "vista iconica", "bonus"],
      alias: ["veu da noiva", "véu da noiva", "bridal veil madeira"],
      desc: "Vista iconica sulla cascata che cade direttamente in mare. Rapidissima ma molto efficace.",
      tip: "Bonus forte senza rubare troppo tempo. Fermo 5 minuti e hai già preso il colpo d'occhio.",
      longDescription: "Una delle cascate più fotogeniche di Madeira per la sua particolarità: cade direttamente in mare. Non richiede nulla dal punto di vista fisico, ma il colpo d'occhio è forte e immediato.",
      photoTips: "Composizione semplice: cascata, mare e scogliera. Funziona bene con qualsiasi luce non troppo dura.",
      experience: { wow: 6, tipo: "cascata panoramica", tempo: "5-15 min", mood: "scenico" },
      whenToGo: { best: "giorno", note: "Funziona bene quasi sempre. Evita solo luce dura di mezzogiorno." },
      whenToAvoid: ["mezzogiorno con sole diretto"],
      access: { difficolta: "facile", parcheggio: "vicino", walk: "2 min", strada: "asfaltata" },
      crowd: { best: "mattina presto o tardo pomeriggio", worst: "orari bus turistici" },
      smartTips: [
        "Non deviare apposta: usalo come stop naturale nella strada del nord.",
        "5 minuti ben spesi se sei già in zona.",
        "Ottimo in combo con Porto Moniz o Seixal."
      ],
      image: "https://picsum.photos/seed/Veu-da-Noiva-Madeira/900/600"
    },

    {
      id: "extra-1",
      name: "Cais do Sardinha",
      zone: "est",
      light: "alba",
      activity: "trekking",
      difficulty: "medio",
      level: "extra",
      priority: 4,
      lat: 32.7457,
      lon: -16.6889,
      tags: ["sao lourenco finale", "ocean tip", "trekking est", "remote"],
      alias: ["cais sardinha", "sardinha pier", "sao lourenco end"],
      desc: "Il finale appagante del trekking di São Lourenço. Solo se fai davvero il percorso.",
      tip: "Extra serio solo se completi São Lourenço. Non ha senso venirci apposta.",
      longDescription: "La punta finale del percorso di São Lourenço. Se arrivi qui hai già fatto gran parte del trekking e la sensazione di essere all'estremo est dell'isola, sull'oceano, è molto forte. Non vale come stop autonomo.",
      photoTips: "Vista sull'oceano aperto in tutte le direzioni. Meglio con luce bassa e mare vivo.",
      experience: { wow: 7, tipo: "punta trekking", tempo: "incluso in São Lourenço", mood: "epico" },
      whenToGo: { best: "alba", note: "Solo se fai il percorso completo di São Lourenço." },
      whenToAvoid: ["come stop autonomo senza fare il trekking"],
      access: { difficolta: "medio", parcheggio: "non applicabile", walk: "finale del percorso São Lourenço", strada: "non applicabile" },
      crowd: { best: "prestissimo", worst: "metà mattina" },
      smartTips: [
        "Ha senso solo come conclusione di São Lourenço.",
        "Non pianificarlo come spot separato.",
        "Se arrivi qui, hai già vissuto il meglio."
      ],
      image: "https://picsum.photos/seed/Cais-do-Sardinha-Madeira/900/600"
    },

  ]
};